import {subscriptionPlans,planFeatures,canManageBilling} from './lib/plans'
import {managerLink} from './lib/manualBilling'
import {useStudioTimezone} from './lib/StudioTimezone'
import {t,localeTag} from './i18n/core'
import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
type Subscription={plan:string;status:string;trial_ends_at:string|null;current_period_end:string|null;staff_limit:number|null}
const plans=subscriptionPlans
export default function BillingPage({tenantId,role}:{tenantId:string|null;role:string|null}){
 const timezone=useStudioTimezone(),allowed=canManageBilling(role)
 const [staffCount,setStaffCount]=useState(0)
 const onlinePayment=import.meta.env.VITE_BILLING_MODE==='wayforpay',contact=import.meta.env.VITE_BILLING_TELEGRAM||'detailflow'
 const [sub,setSub]=useState<Subscription|null>(null),[orders,setOrders]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true)
 async function load(){if(!allowed||!supabase||!tenantId){setLoading(false);return}setError('');const result=await supabase.rpc('get_studio_billing',{studio:tenantId});setLoading(false);if(result.error){setError(t('Не вдалося завантажити тариф. Оновіть сторінку або зверніться до підтримки.'));return}setSub(result.data.subscription);setStaffCount(result.data.staff_count);setOrders(result.data.orders||[])}
 useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>clearInterval(t)},[tenantId,role])
 async function pay(plan:string){if(!supabase||busy||!allowed)return;setBusy(plan);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Увійдіть повторно.');const r=await fetch('/api/wayforpay/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({tenantId,plan})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Не вдалося створити платіж');if(result.action!=='https://secure.wayforpay.com/pay')throw new Error('Невідома адреса оплати');const form=document.createElement('form');form.method='POST';form.action=result.action;for(const [name,value] of Object.entries(result.fields)){for(const item of Array.isArray(value)?value:[value]){const input=document.createElement('input');input.type='hidden';input.name=Array.isArray(value)?name+'[]':name;input.value=String(item);form.append(input)}}document.body.append(form);form.submit()}catch(e){setError(e instanceof Error?e.message:t("Не вдалося відкрити оплату"));setBusy('')}}
 if(!allowed)return null
 const end=sub?.status==='trialing'?sub.trial_ends_at:sub?.current_period_end,active=!!end&&new Date(end).getTime()>Date.now()&&['active','trialing'].includes(sub?.status||'')
 return <section className="content"><h1>{t("Тариф і білінг")}</h1>{loading?<p>{t("Завантажуємо підписку…")}</p>:<section className="panel"><h2>{active?t(sub?.status==='trialing'?'Пробний період':'Підписка активна'):t("Потрібне продовження")}</h2><p>{end?`${t("Доступ до")} ${new Date(end).toLocaleDateString(localeTag(),{timeZone:timezone})}`:t("Оплачений період відсутній")}{t(". Поточний тариф: ")}{sub?.plan||'—'}.</p><p>{t("Активних майстрів")}: {staffCount} / {sub?(sub.staff_limit??t("Без ліміту")):'—'}</p><p>{t("Після завершення періоду збережені дані доступні; нові записи й активація майстрів потребують продовження.")}</p><button className="text-btn" onClick={()=>void load()}>{t("Оновити статус доступу")}</button></section>}{error&&<p role="alert">{t(error)}</p>}<p>{t("Усі тарифи включають однакові функції. Відрізняється лише кількість активних майстрів. Власник і адміністратори не займають місця майстрів; запрошені активні профілі займають.")}</p><div className="team-grid">{plans.map(p=><article className="panel settings" key={p.id}><h2>{p.name}</h2><strong>{p.price.toLocaleString(localeTag())}{t(" ₴ / місяць")}</strong><p>{t(p.limit)}</p><ul>{planFeatures.map(feature=><li key={feature}>{t(feature)}</li>)}</ul>{p.staffLimit!==null&&staffCount>p.staffLimit&&<p role="status">{t("Для цього тарифу спочатку деактивуйте зайві профілі майстрів.")}</p>}{onlinePayment?<button className="primary" disabled={!allowed||!!busy||loading||!!error||(p.staffLimit!==null&&staffCount>p.staffLimit)} onClick={()=>void pay(p.id)}>{busy===p.id?t("Відкриваємо оплату…"):`${t("Оплатити")} ${p.price} ₴`}</button>:allowed&&managerLink(contact,'')?<a className="primary" target="_blank" rel="noopener noreferrer" href={managerLink(contact,`Detailflow: прошу підключити тариф ${p.name} на 1 місяць (${p.price} грн). Студія: ${tenantId||'вкажу у розмові'}.`)}>{t('Звернутися в Telegram')}</a>:<p>{t('Для підключення тарифу зверніться до менеджера Detailflow.')}</p>}</article>)}</div><p>{onlinePayment?t("Разова оплата одного місяця через WayForPay. Автоматичних списань немає. Продовження додає місяць до невикористаного оплаченого періоду. Платіж підтверджується після відповіді провайдера."):t("Підключення та продовження — через менеджера. Узгодьте тариф і спосіб оплати в Telegram. Після підтвердження менеджер активує доступ; залишок періоду зберігається.")}</p>{!allowed&&<p>{t("Тариф доступний власнику та адміністратору студії.")}</p>}<section className="panel"><h2>{t("Історія онлайн-платежів")}</h2>{orders.map(o=><p key={o.id}>{new Date(o.created_at).toLocaleDateString(localeTag(),{timeZone:timezone})} · {o.plan} · {o.amount} ₴ · {t(({approved:'Оплачено',created:'Очікує оплати',declined:'Не оплачено',expired:'Строк минув'} as Record<string,string>)[o.status]||o.status)}</p>)}{!orders.length&&<p>{t("Платежів ще немає.")}</p>}</section></section>
}
