import {managerLink} from './lib/manualBilling'
import {useStudioTimezone} from './lib/StudioTimezone'
import {t,localeTag} from './i18n/core'
import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
type Subscription={plan:string;status:string;trial_ends_at:string|null;current_period_end:string|null}
const plans=[{id:'start',name:'Start',price:690,limit:'До 3 майстрів'},{id:'studio',name:'Studio',price:1490,limit:'До 10 майстрів'},{id:'pro',name:'Pro',price:2990,limit:'Без ліміту майстрів'}]
export default function BillingPage({tenantId,owner}:{tenantId:string|null;owner:boolean}){
 const timezone=useStudioTimezone()
 const onlinePayment=import.meta.env.VITE_BILLING_MODE==='wayforpay',contact=import.meta.env.VITE_BILLING_TELEGRAM||'detailflow'
 const [sub,setSub]=useState<Subscription|null>(null),[orders,setOrders]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true)
 async function load(){if(!supabase||!tenantId){setLoading(false);return}setError('');const [a,b]=await Promise.all([supabase.from('subscriptions').select('plan,status,trial_ends_at,current_period_end').eq('tenant_id',tenantId).maybeSingle(),supabase.from('payment_orders').select('id,plan,amount,status,created_at,paid_at').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(30)]);setLoading(false);if(a.error||b.error){setError(t("Не вдалося завантажити підписку. Перевірте оновлення бази 034."));return}setSub(a.data);setOrders(b.data||[])}
 useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>clearInterval(t)},[tenantId])
 async function pay(plan:string){if(!supabase||busy||!owner)return;setBusy(plan);setError('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Увійдіть повторно.');const r=await fetch('/api/wayforpay/checkout',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({tenantId,plan})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Не вдалося створити платіж');if(result.action!=='https://secure.wayforpay.com/pay')throw new Error('Невідома адреса оплати');const form=document.createElement('form');form.method='POST';form.action=result.action;for(const [name,value] of Object.entries(result.fields)){for(const item of Array.isArray(value)?value:[value]){const input=document.createElement('input');input.type='hidden';input.name=Array.isArray(value)?name+'[]':name;input.value=String(item);form.append(input)}}document.body.append(form);form.submit()}catch(e){setError(e instanceof Error?e.message:t("Не вдалося відкрити оплату"));setBusy('')}}
 const end=sub?.status==='trialing'?sub.trial_ends_at:sub?.current_period_end,active=!!end&&new Date(end).getTime()>Date.now()&&['active','trialing'].includes(sub?.status||'')
 return <section className="content"><h1>{t("Тариф і білінг")}</h1>{loading?<p>{t("Завантажуємо підписку…")}</p>:<section className="panel"><h2>{active?t(sub?.status==='trialing'?'Пробний період':'Підписка активна'):t("Потрібне продовження")}</h2><p>{end?`${t("Доступ до")} ${new Date(end).toLocaleDateString(localeTag(),{timeZone:timezone})}`:t("Оплачений період відсутній")}{t(". Поточний тариф: ")}{sub?.plan||'—'}.</p><p>{t("Після завершення періоду збережені дані доступні; нові записи й активація майстрів потребують продовження.")}</p><button className="text-btn" onClick={()=>void load()}>{t("Оновити статус доступу")}</button></section>}{error&&<p role="alert">{t(error)}</p>}<div className="team-grid">{plans.map(p=><article className="panel settings" key={p.id}><h2>{p.name}</h2><strong>{p.price.toLocaleString(localeTag())}{t(" ₴ / місяць")}</strong><p>{t(p.limit)}</p>{onlinePayment?<button className="primary" disabled={!owner||!!busy||loading||!!error} onClick={()=>void pay(p.id)}>{busy===p.id?t("Відкриваємо оплату…"):`${t("Оплатити")} ${p.price} ₴`}</button>:owner&&managerLink(contact,'')?<a className="primary" target="_blank" rel="noopener noreferrer" href={managerLink(contact,`Detailflow: прошу підключити тариф ${p.name} на 1 місяць (${p.price} грн). Студія: ${tenantId||'вкажу у розмові'}.`)}>{t('Звернутися в Telegram')}</a>:<p>{t('Для підключення тарифу зверніться до менеджера Detailflow.')}</p>}</article>)}</div><p>{onlinePayment?t("Разова оплата одного місяця через WayForPay. Автоматичних списань немає. Продовження додає місяць до невикористаного оплаченого періоду. Платіж підтверджується після відповіді провайдера."):t("Підключення та продовження — через менеджера. Узгодьте тариф і спосіб оплати в Telegram. Після підтвердження менеджер активує доступ; залишок періоду зберігається.")}</p>{!owner&&<p>{t("Оплату тарифу виконує власник студії.")}</p>}<section className="panel"><h2>{t("Історія онлайн-платежів")}</h2>{orders.map(o=><p key={o.id}>{new Date(o.created_at).toLocaleDateString(localeTag(),{timeZone:timezone})} · {o.plan} · {o.amount} ₴ · {t(({approved:'Оплачено',created:'Очікує оплати',declined:'Не оплачено',expired:'Строк минув'} as Record<string,string>)[o.status]||o.status)}</p>)}{!orders.length&&<p>{t("Платежів ще немає.")}</p>}</section></section>
}
