import {useEffect,useState} from 'react'
import {t,localeTag} from './i18n/core'
import {supabase} from './lib/supabase'
import {financeDay} from './lib/finance'
import {useStudioTimezone} from './lib/StudioTimezone'
import {DateInput} from './components/FormInputs'
import {previousPeriod,percentChange,completeMonths} from './lib/analyticsPeriods'
import {xlsxReport,pdfReport,type ReportSheet} from './lib/analyticsExport'
import './business-analytics.css'

export type Report={timezone:string;orders:number;revenue:number;late_orders:number;dated_orders:number;
 clients:{id:string;name:string;visits:number;revenue:number;lifetime_visits:number;lifetime_value:number;returning:boolean}[];
 masters:{staff_id:string|null;name:string;jobs:number;revenue:number;seconds:number;timed_jobs:number;timed_revenue:number|null;orders?:number;average_order?:number|null;cancelled_orders?:number}[];
 services:{title:string;jobs:number;measured:number;planned:number|null;actual:number|null;exceeded:number}[];
 demand:{weekday:number;booking_hour:number;bookings:number;cancelled:number}[];months:{month:string;orders:number;revenue:number}[]}
const n=(value:number|null)=>value===null?'—':new Intl.NumberFormat(localeTag(),{maximumFractionDigits:1}).format(value)
export default function BusinessAnalytics({tenantId,preview}:{tenantId?:string|null;preview?:Report}){
 const timezone=useStudioTimezone(),today=financeDay(new Date().toISOString(),timezone)
 const [from,setFrom]=useState(today.slice(0,7)+'-01'),[to,setTo]=useState(today),[period,setPeriod]=useState({from:today.slice(0,7)+'-01',to:today})
 const [previous,setPrevious]=useState<Report|null>(null),[exporting,setExporting]=useState(false),[clientLimit,setClientLimit]=useState(50)
 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[version,setVersion]=useState(0)
 useEffect(()=>{let live=true;setData(null);setPrevious(null);setClientLimit(50);setError('');setLoading(false);if(import.meta.env.DEV&&preview){setData(preview);setPrevious({...preview,orders:20,revenue:35000});return}if(!supabase||!tenantId){setError('Для звіту підключіть студію.');return}setLoading(true)
 const prior=previousPeriod(period.from,period.to)
 void Promise.all([supabase.rpc('business_analytics_v2',{studio:tenantId,date_from:period.from,date_to:period.to}),supabase.rpc('business_analytics_v2',{studio:tenantId,date_from:prior.from,date_to:prior.to})]).then(([current,last])=>{if(!live)return;setLoading(false);if(current.error||last.error)setError('Звіт недоступний. Перевірте підключення, фінансові права та оновлення бази.');else {setData(current.data as Report);setPrevious(last.data as Report)}}).catch(()=>{if(live){setLoading(false);setError('Звіт недоступний. Перевірте підключення, фінансові права та оновлення бази.')}})
 return()=>{live=false}
 },[tenantId,period,version,preview])
 const valid=!!from&&!!to&&from<=to&&(Date.parse(to)-Date.parse(from))/86400000<=1095
 const tables=data?[
  {name:t('Майстри'),headers:['Майстер','Роботи','Вартість робіт, ₴','Години','Роботи з таймером','Вартість за годину, ₴','Замовлення','Середня частка замовлення, ₴','Скасовані замовлення'],rows:data.masters.map(r=>[r.name,r.jobs,r.revenue,r.seconds/3600,r.timed_jobs,r.seconds>0?(r.timed_revenue||0)/(r.seconds/3600):'—',r.orders??0,r.average_order??'—',r.cancelled_orders??0])},
  {name:t('Час послуг'),headers:['Послуга','Роботи','Виміряно','План, хв','Факт, хв','Перевищення плану'],rows:data.services.map(r=>[r.title,r.jobs,r.measured,r.planned??'—',r.actual??'—',r.exceeded])},
  {name:t('Клієнти'),headers:['Клієнт','Візити','Вартість робіт, ₴','Середній чек, ₴','Візити за всю історію','Історична вартість, ₴'],rows:data.clients.map(r=>[r.name,r.visits,r.revenue,r.revenue/r.visits,r.lifetime_visits,r.lifetime_value])},
  {name:t('Сезонність'),headers:['Місяць','Замовлення','Вартість робіт, ₴'],rows:completeMonths(data.months,period.from,period.to).map(r=>[r.month,r.orders,r.revenue])}
 ]:[]
 function reportSheets():ReportSheet[]{if(!data)return [];return [{name:t('Період'),rows:[[t('Від'),period.from],[t('До'),period.to],[t('Часовий пояс студії'),data.timezone],['UAH'],[t('Вартість завершених замовлень'),data.revenue],[t('Замовлення'),data.orders],[t('Попередній період'),previousPeriod(period.from,period.to).from+' — '+previousPeriod(period.from,period.to).to],[t('Вартість у попередньому періоді'),previous?.revenue??'—']]},...tables.map(s=>({name:s.name,rows:[s.headers.map(h=>t(h)),...s.rows]})),{name:t('Попит'),rows:[[t('День тижня'),t('Година'),t('Записи'),t('Скасовано')],...data.demand.map(r=>[r.weekday,r.booking_hour,r.bookings,r.cancelled])]}]}
 async function download(kind:'xlsx'|'pdf'){if(!data||exporting)return;setExporting(true);setError('');try{const sheets=reportSheets();let bytes:Uint8Array;if(kind==='xlsx')bytes=xlsxReport(sheets);else {const response=await fetch('/fonts/NotoSans.ttf');if(!response.ok)throw new Error('font');bytes=await pdfReport(sheets,new Uint8Array(await response.arrayBuffer()),'Detailflow · '+t('Аналітика студії'))}const url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:kind==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='detailflow-'+period.from+'-'+period.to+'.'+kind;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch{setError('Не вдалося створити файл. Спробуйте ще раз.')}finally{setExporting(false)}}
 return <div className="business-analytics">
  <form className="panel finance-period analytics-controls" onSubmit={e=>{e.preventDefault();if(valid){setPeriod({from,to});setVersion(v=>v+1)}}}>
   <label>{t('Від')}<DateInput type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)}/></label><label>{t('До')}<DateInput type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><button className="primary" disabled={!valid||loading}>{t('Оновити звіт')}</button><small>{t('Період до трьох років. Часовий пояс студії.')}</small>
  </form>
  {loading&&<p role="status">{t('Завантаження…')}</p>}{error&&<p role="alert" className="panel">{t(error)}</p>}
  {data&&<><header className="analytics-report-title"><div><h2>{t('Аналітика студії')}</h2><p>{period.from} — {period.to} · {data.timezone} · UAH</p></div><div className="analytics-controls"><button className="secondary" disabled={exporting} onClick={()=>void download('xlsx')}>{t('Експорт XLSX')}</button><button className="secondary" disabled={exporting} onClick={()=>void download('pdf')}>{t('Завантажити PDF')}</button></div></header>
   <div className="finance-kpis">{[[t('Завершені замовлення'),data.orders],[t('Вартість завершених замовлень'),data.revenue],[t('Середній чек, ₴'),data.orders?data.revenue/data.orders:null],[t('Повторні клієнти, %'),data.clients.length?100*data.clients.filter(c=>c.returning||c.visits>1).length/data.clients.length:null]].map(([title,value])=><section className="panel" key={String(title)}><p>{title}</p><h2>{n(value as number|null)}</h2></section>)}</div>
   {previous&&<section className="panel"><h2>{t('Порівняння періодів')}</h2><p>{t('Попередній період')}: {previousPeriod(period.from,period.to).from} — {previousPeriod(period.from,period.to).to}</p><div className="finance-kpis">{[[t('Замовлення'),data.orders,previous.orders],[t('Вартість робіт, ₴'),data.revenue,previous.revenue],[t('Середній чек, ₴'),data.orders?data.revenue/data.orders:0,previous.orders?previous.revenue/previous.orders:0]].map(([label,current,last])=><div key={String(label)}><p>{label}</p><b>{n(Number(last))} → {n(Number(current))}</b><p>{percentChange(Number(current),Number(last))===null?t('Немає бази порівняння'):n(percentChange(Number(current),Number(last)))+'%'}</p></div>)}</div></section>}
   <section className="panel"><h2>{t('Динаміка вартості робіт')}</h2><div className="analytics-month-chart">{completeMonths(data.months,period.from,period.to).map(r=><div key={r.month}><span>{r.month}</span><div className="finance-track"><span style={{width:(r.revenue/Math.max(1,...data.months.map(m=>m.revenue))*100)+'%'}}/></div><b>{n(r.revenue)} ₴</b></div>)}</div></section>
   <p className="panel">{t('Середня частка замовлення — вартість робіт майстра, поділена на кількість його замовлень. Скасування показують причетність до замовлення, а не провину майстра.')}</p>
   <p className="panel">{t('Завершено із запізненням')}: <b>{data.late_orders} / {data.dated_orders}</b> · {t('Замовлення з указаним терміном готовності')}</p>
   <details className="panel" open><summary>{t('Як розраховані показники')}</summary><p>{t('Вартість завершених робіт — не отримані оплати. Грошові надходження та прибуток дивіться в огляді фінансів.')}</p><p>{t('Повторні клієнти мають попередній завершений візит або кілька візитів у періоді. Історична вартість — сума завершених замовлень до кінця періоду, без прогнозу LTV.')}</p><p>{t('Години — активний час підтверджених робіт. Вартість за годину враховує лише роботи з таймером. План зберігається для нових робіт із каталогу; для старих робіт може бути відсутній.')}</p></details>
   {tables.map(table=><section className="panel" key={table.name}><h2>{table.name}</h2>{table.rows.length?<div className="finance-table-scroll"><table><thead><tr>{table.headers.map(h=><th key={h}>{t(h)}</th>)}</tr></thead><tbody>{table.rows.slice(0,table.name===t('Клієнти')?clientLimit:table.rows.length).map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{typeof v==='number'?n(v):v}</td>)}</tr>)}</tbody></table>{table.name===t('Клієнти')&&table.rows.length>clientLimit&&<button className="text-btn" onClick={()=>setClientLimit(v=>v+50)}>{t('Показати ще')}</button>}</div>:<p>{t('Немає даних за цей період')}</p>}</section>)}
   <section className="panel"><h2>{t('Попит за днями та годинами')}</h2><p>{t('Кількість записів за часом початку. Скасовані записи виключено; це не відсоток завантаження.')}</p><div className="analytics-heatmap">{['Пн','Вт','Ср','Чт','Пт','Сб','Нд'].map((day,i)=><div className="analytics-heat-row" key={day}><b>{t(day)}</b>{Array.from({length:24},(_,hour)=>{const r=data.demand.find(r=>r.weekday===i+1&&r.booking_hour===hour),value=r?r.bookings-r.cancelled:0,max=Math.max(1,...data.demand.map(r=>r.bookings-r.cancelled));return <span key={hour} title={`${t(day)} ${hour}:00 · ${value}`} style={{background:`rgba(169,215,85,${value?.15+.75*value/max:.04})`}}><small>{hour}</small><b>{value||'·'}</b></span>})}</div>)}</div><p>{t('Скасовано')}: {data.demand.reduce((sum,r)=>sum+r.cancelled,0)}</p></section>
  </>}
 </div>
}
