import { FormEvent, useMemo, useState } from 'react'
import { Plus, X } from 'lucide-react'

export type LeadStatus='new'|'in_progress'|'deferred'|'won'|'lost'
export type Lead={id:string|number;clientId:string|number|null;clientName:string;staffId:string|number|null;staffName:string;title:string;phone:string;source:string;status:LeadStatus;priority:'normal'|'urgent';dueAt:string;notes:string;createdAt:string}
type Person={id:string|number;name:string;phone?:string}
const columns:{status:LeadStatus;title:string;color:string}[]=[{status:'new',title:'Нові',color:'blue'},{status:'in_progress',title:'У роботі',color:'green'},{status:'deferred',title:'Відкладені',color:'orange'},{status:'won',title:'Успішні',color:'gray'}]
const labels:Record<LeadStatus,string>={new:'Нове',in_progress:'У роботі',deferred:'Відкладено',won:'Успішно',lost:'Втрачено'}

export default function Leads({items,clients,staff,add,update,remove}:{items:Lead[];clients:Person[];staff:Person[];add:(lead:Lead)=>Promise<string>;update:(id:Lead['id'],patch:Partial<Pick<Lead,'status'|'staffId'|'dueAt'|'priority'|'notes'>>)=>Promise<string>;remove:(id:Lead['id'])=>Promise<string>}) {
  const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[showLost,setShowLost]=useState(false),[message,setMessage]=useState('')
  const visible=useMemo(()=>items.filter(item=>(showLost||item.status!=='lost')&&[item.title,item.clientName,item.phone,item.source,item.staffName].join(' ').toLowerCase().includes(query.toLowerCase())),[items,query,showLost])
  async function change(item:Lead,status:LeadStatus){const error=await update(item.id,{status});setMessage(error||'Статус звернення оновлено.')}
  async function deleteItem(id:Lead['id']){if(!window.confirm('Видалити звернення?'))return;const error=await remove(id);setMessage(error||'Звернення видалено.')}
  return <section className="content leads-page"><div className="page-title"><div><p>Продажі та комунікація</p><h1>Звернення</h1></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/> Нове звернення</button></div><div className="panel order-toolbar"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Пошук за клієнтом, телефоном, джерелом"/><label><input type="checkbox" checked={showLost} onChange={event=>setShowLost(event.target.checked)}/> Показувати втрачені</label></div>{message&&<p role="status" className="task-message">{message}</p>}<div className="lead-board">{columns.map(column=>{const rows=visible.filter(item=>item.status===column.status);return <section className={'lead-column '+column.color} key={column.status}><div className="task-column-head"><div><h2>{column.title}</h2><small>{rows.length} звернень</small></div><b>{rows.length}</b></div>{rows.map(item=><LeadCard key={item.id} item={item} update={change} remove={deleteItem}/>) }{!rows.length&&<p className="task-empty">Немає звернень</p>}</section>})}</div>{showLost&&visible.filter(item=>item.status==='lost').length>0&&<section className="panel cancelled-orders"><h2>Втрачені звернення</h2>{visible.filter(item=>item.status==='lost').map(item=><LeadCard key={item.id} item={item} update={change} remove={deleteItem}/>)}</section>}{open&&<LeadModal clients={clients} staff={staff} close={()=>setOpen(false)} add={async lead=>{const error=await add(lead);if(!error)setOpen(false);return error}}/>}</section>
}

function LeadCard({item,update,remove}:{item:Lead;update:(item:Lead,status:LeadStatus)=>Promise<void>;remove:(id:Lead['id'])=>Promise<void>}){return <article className="lead-card"><div className="task-card-top"><small>{item.source}</small><button className="text-btn" onClick={()=>void remove(item.id)} aria-label="Видалити звернення">×</button></div><b>{item.title}</b><p>{item.clientName||item.phone||'Клієнта не вказано'}</p>{item.notes&&<p>{item.notes}</p>}<div className="order-card-details"><span>{item.staffName||'Менеджера не призначено'}</span>{item.dueAt&&<span className={new Date(item.dueAt).getTime()<Date.now()&&!['won','lost'].includes(item.status)?'overdue':''}>Контакт до: {new Date(item.dueAt).toLocaleDateString('uk-UA',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</span>}</div>{item.priority==='urgent'&&<span className="priority-badge urgent">Терміново</span>}<select value={item.status} onChange={event=>void update(item,event.target.value as LeadStatus)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></article>}
function LeadModal({clients,staff,close,add}:{clients:Person[];staff:Person[];close:()=>void;add:(lead:Lead)=>Promise<string>}){const [clientId,setClientId]=useState(''),[staffId,setStaffId]=useState(''),[title,setTitle]=useState(''),[phone,setPhone]=useState(''),[source,setSource]=useState('Instagram'),[priority,setPriority]=useState<'normal'|'urgent'>('normal'),[dueAt,setDueAt]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);const client=clients.find(item=>String(item.id)===clientId),member=staff.find(item=>String(item.id)===staffId);async function submit(event:FormEvent){event.preventDefault();if(!title.trim()){setError('Вкажіть тему звернення.');return}setSaving(true);const result=await add({id:Date.now(),clientId:client?.id||null,clientName:client?.name||'',staffId:member?.id||null,staffName:member?.name||'',title:title.trim(),phone:phone.trim()||client?.phone||'',source,status:'new',priority,dueAt:dueAt?new Date(dueAt).toISOString():'',notes:notes.trim(),createdAt:new Date().toISOString()});setSaving(false);if(result)setError(result)}return <div className="overlay"><form className="modal lead-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}><X size={20}/></button><p>Звернення клієнта</p><h2>Нове звернення</h2><label>Клієнт<select value={clientId} onChange={event=>setClientId(event.target.value)}><option value="">Новий клієнт / не обрано</option>{clients.map(item=><option key={item.id} value={String(item.id)}>{item.name}</option>)}</select></label><label>Тема *<input required value={title} onChange={event=>setTitle(event.target.value)} placeholder="Наприклад, запит на полірування авто"/></label><label>Телефон<input value={phone} onChange={event=>setPhone(event.target.value)} placeholder={client?.phone||'+380...'}/></label><label>Джерело<select value={source} onChange={event=>setSource(event.target.value)}><option>Instagram</option><option>Google</option><option>Рекомендація</option><option>Дзвінок</option><option>Сайт</option><option>Вручну</option></select></label><label>Відповідальний<select value={staffId} onChange={event=>setStaffId(event.target.value)}><option value="">Не призначено</option>{staff.map(item=><option key={item.id} value={String(item.id)}>{item.name}</option>)}</select></label><label>Крайній термін контакту<input type="datetime-local" value={dueAt} onChange={event=>setDueAt(event.target.value)}/></label><label><span>Пріоритет</span><select value={priority} onChange={event=>setPriority(event.target.value as 'normal'|'urgent')}><option value="normal">Звичайний</option><option value="urgent">Терміновий</option></select></label><label>Коментар<textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Деталі запиту та наступний крок"/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={saving}>{saving?'Зберігаємо…':'Створити звернення'}</button></form></div>}
