import { useMemo, useState } from 'react'
import { CheckCircle2, Clock3, Play, WalletCards } from 'lucide-react'
import type { ChecklistItem, WorkOrder, WorkOrderStatus } from './WorkOrders'

type Staff={id:string|number;name:string;color:string;speciality:string}
type Shift={id:string;staffId:string;startedAt:string;endedAt:string|null}
type Earning={id:string;staffId:string;workOrderId:string;amount:number;status:string;accruedAt:string}
const money=(value:number)=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(value)+' ₴'

export default function MasterCabinet({staff,orders,shifts,earnings,toggleShift,updateOrder}:{staff:Staff|null;orders:WorkOrder[];shifts:Shift[];earnings:Earning[];toggleShift:(staffId:string,shift:Shift|undefined)=>Promise<string>;updateOrder:(id:WorkOrder['id'],patch:Partial<Pick<WorkOrder,'status'|'checklist'|'submittedForReviewAt'>>)=>Promise<string>}){
  const [message,setMessage]=useState('')
  const mine=useMemo(()=>staff?orders.filter(order=>String(order.staffId)===String(staff.id)&&!['ready','issued','cancelled'].includes(order.status)):[],[staff,orders])
  const mineEarnings=useMemo(()=>staff?earnings.filter(item=>String(item.staffId)===String(staff.id)&&item.status==='accrued'):[],[staff,earnings])
  const openShift=staff?shifts.find(item=>String(item.staffId)===String(staff.id)&&!item.endedAt):undefined
  const accrued=mineEarnings.reduce((sum,item)=>sum+item.amount,0)
  async function changeShift(){if(!staff)return;setMessage(await toggleShift(String(staff.id),openShift))}
  async function toggleCheck(order:WorkOrder,item:ChecklistItem){const checklist=order.checklist.map(entry=>entry.id===item.id?{...entry,done:!entry.done}:entry);setMessage(await updateOrder(order.id,{checklist,status:order.status==='assigned'?'in_progress':order.status}))}
  async function submit(order:WorkOrder){if(order.checklist.some(item=>!item.done)){setMessage('Спочатку позначте всі пункти чек-листа.');return}setMessage(await updateOrder(order.id,{status:'review' as WorkOrderStatus,submittedForReviewAt:new Date().toISOString()}))}
  if(!staff)return <section className="content"><div className="page-title"><div><p>Мобільний робочий простір</p><h1>Кабінет майстра</h1></div></div><div className="panel master-empty"><div><b>Перевірте запрошення на email</b><p>Власник створює профіль майстра та надсилає лист для реєстрації. Перейдіть за посиланням у листі, задайте пароль і увійдіть тим самим email. Якщо листа немає або доступ заблоковано — зверніться до власника студії.</p></div></div></section>
  return <section className="content master-cabinet"><div className="page-title"><div><p>{staff.speciality}</p><h1>Привіт, {staff.name.split(' ')[0]}</h1></div><button className={openShift?'master-shift active':'master-shift'} onClick={()=>void changeShift()}><Clock3 size={17}/>{openShift?'Завершити зміну':'Почати зміну'}</button></div>{message&&<p className="task-message" role="status">{message}</p>}<div className="master-metrics"><div><span>На зміні</span><b>{openShift?new Date(openShift.startedAt).toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'}):'Не розпочато'}</b></div><div><span>Мої авто</span><b>{mine.length}</b></div><div><span>Нараховано</span><b>{money(accrued)}</b></div></div><div className="master-orders"><h2>Мої призначені роботи</h2>{mine.map(order=>{const complete=order.checklist.filter(item=>item.done).length;return <article className="master-order" key={String(order.id)}><header><div><b>{order.vehicle||order.title}</b><small>{order.clientName} · {order.title}</small></div><strong>{complete}/{order.checklist.length||0}</strong></header>{order.notes&&<p>{order.notes}</p>}<div className="master-checklist">{order.checklist.length?order.checklist.map(item=><label key={item.id}><input type="checkbox" checked={item.done} onChange={()=>void toggleCheck(order,item)}/><span>{item.title}</span></label>):<p>Чек-лист ще не додано власником.</p>}</div>{order.status==='review'?<div className="master-review"><CheckCircle2 size={18}/><span>Роботу відправлено на перевірку власнику.</span></div>:<button className="primary" disabled={!openShift||!order.checklist.length||complete!==order.checklist.length} onClick={()=>void submit(order)}><Play size={16}/> Відправити на перевірку</button>}</article>})}{!mine.length&&<div className="panel master-empty"><CheckCircle2 size={20}/><div><b>Активних робіт немає</b><p>Нові призначення від власника з’являться тут.</p></div></div>}</div><div className="master-earned"><h2><WalletCards size={19}/> Нарахування</h2>{mineEarnings.map(item=>{const order=orders.find(entry=>String(entry.id)===item.workOrderId);return <div key={item.id}><span>{order?.vehicle||order?.title||'Виконана робота'}<small>{new Date(item.accruedAt).toLocaleDateString('uk-UA')}</small></span><b>{money(item.amount)}</b></div>})}{!mineEarnings.length&&<p>Після перевірки робіт власником суми з’являться тут.</p>}</div></section>
}
