import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {t,localeTag} from './i18n/core'
import {Select} from './components/Select'
import {EvidenceFile} from './workflow/JobEvidence'
import type {JobMedia,PaintReading} from './workflow/model'
type Row={job_id:string;order_id:string;title:string;vehicle:string;client:string;staff:string;media:JobMedia;readings:PaintReading[]}
export default function MediaArchive({tenantId}:{tenantId:string}){
 const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[phase,setPhase]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(0),[rows,setRows]=useState<Row[]>([]),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0)
 useEffect(()=>{let live=true;setBusy(true);setRows([]);setError('');if(!supabase){setBusy(false);return}void supabase.rpc('job_media_archive',{studio:tenantId,query_input:search,phase_input:phase,kind_input:kind,offset_input:page*50}).then(r=>{if(!live)return;setBusy(false);if(r.error){setError(t('Не вдалося завантажити архів'));return}const data=(r.data||[]) as Row[];setRows(data.slice(0,50));setMore(data.length>50)});return()=>{live=false}},[tenantId,search,phase,kind,page,refresh])
 return <section className="content"><div className="page-title"><div><p>{t('Історія робіт студії')}</p><h1>{t('Фотоархів')}</h1></div><button className="text-btn" onClick={()=>setRefresh(v=>v+1)}>{t('Оновити')}</button></div><form className="panel evidence-search" onSubmit={e=>{e.preventDefault();setSearch(query.trim());setPage(0)}}><input aria-label={t('Пошук в архіві')} placeholder={t('Авто, клієнт, майстер, робота або номер замовлення')} value={query} onChange={e=>setQuery(e.target.value)}/><Select aria-label={t('Етап матеріалів')} value={phase} onChange={e=>{setPhase(e.target.value);setPage(0)}}><option value="">{t('Всі етапи')}</option><option value="before">{t('До початку робіт')}</option><option value="after">{t('Після роботи')}</option><option value="legacy">{t('Попередні фото без етапу')}</option></Select><Select aria-label={t('Тип файлу')} value={kind} onChange={e=>{setKind(e.target.value);setPage(0)}}><option value="">{t('Фото та відео')}</option><option value="image">{t('Фото')}</option><option value="video">{t('Відео')}</option></Select><button className="primary">{t('Знайти')}</button></form>{busy&&<p role="status">{t('Завантаження…')}</p>}{error&&<p role="alert">{error}</p>}<div className="evidence-archive">{rows.map(r=><article className="panel" key={r.media.path}><b>{r.vehicle||t('Авто не вказано')}</b><p>{r.title} · #{r.order_id.slice(0,8)}</p><p>{t('Клієнт')}: {r.client||'—'}<br/>{t('Майстер')}: {r.staff||'—'}</p><p>{t(r.media.phase==='before'?'До початку робіт':r.media.phase==='after'?'Після роботи':'Попередні фото без етапу')}{r.media.created_at&&' · '+new Date(r.media.created_at).toLocaleDateString(localeTag())}</p><EvidenceFile media={r.media}/>{r.readings.length>0&&<details><summary>{t('Товщина покриття, мкм')}</summary>{r.readings.map((v,i)=><p key={i}>{v.panel}: {v.before??'—'} → {v.after??'—'} {t('мкм')}</p>)}</details>}</article>)}</div>{!busy&&!error&&!rows.length&&<p className="panel">{t('Матеріалів за цим запитом немає')}</p>}<div className="wf-actions"><button disabled={busy||page===0} onClick={()=>setPage(v=>v-1)}>{t('Назад')}</button><span>{page+1}</span><button disabled={busy||!more} onClick={()=>setPage(v=>v+1)}>{t('Далі')}</button></div></section>
}
