import {useStudioTimezone} from './lib/StudioTimezone'
import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {NumberInput} from './components/FormInputs'
import {confirmAction} from './components/Dialogs'
import {t,localeTag} from './i18n/core'
type Settings={email_enabled:boolean;reminder_24h_enabled:boolean;reminder_2h_enabled:boolean;repeat_enabled:boolean}
export default function NotificationSettings({tenantId}:{tenantId:string}){
 const timezone=useStudioTimezone()
 const [settings,setSettings]=useState<Settings|null>(null),[services,setServices]=useState<{id:string;name:string;repeat_interval_months:number|null}[]>([]),[jobs,setJobs]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){if(!supabase)return;const [a,b,c]=await Promise.all([supabase.from('reminder_settings').select('email_enabled,reminder_24h_enabled,reminder_2h_enabled,repeat_enabled').eq('tenant_id',tenantId).maybeSingle(),supabase.from('services').select('id,name,repeat_interval_months').eq('tenant_id',tenantId).eq('active',true).order('name'),supabase.from('notification_jobs').select('id,kind,status,attempts,next_attempt_at,created_at,expires_at').eq('tenant_id',tenantId).order('created_at',{ascending:false}).limit(30)]);if(a.error||b.error||c.error){setError(t('Не вдалося завантажити налаштування повідомлень.'));return}setError('');setSettings(a.data||{email_enabled:true,reminder_24h_enabled:true,reminder_2h_enabled:true,repeat_enabled:false});setServices(b.data||[]);setJobs(c.data||[])}
 useEffect(()=>{void load()},[tenantId])
 async function save(){if(!supabase||!settings||busy)return;setBusy(true);setError('');setMessage('');const r=await supabase.from('reminder_settings').upsert({tenant_id:tenantId,...settings},{onConflict:'tenant_id'}).select('tenant_id').single();setBusy(false);if(r.error)setError(r.error.message);else setMessage(t('Налаштування збережено.'))}
 async function interval(id:string,value:string){if(!supabase||busy)return;setBusy(true);setError('');const r=await supabase.from('services').update({repeat_interval_months:value?Number(value):null}).eq('tenant_id',tenantId).eq('id',id).select('id').single();setBusy(false);if(r.error)setError(r.error.message);else setMessage(t('Інтервал збережено.'))}
 async function retry(job:any){if(!supabase||busy)return;if(job.status==='uncertain'&&!await confirmAction(t('Провайдер міг уже прийняти це повідомлення. Перевірте його журнал перед повтором, щоб не надіслати дублікат. Повторити?')))return;setBusy(true);setError('');const r=await supabase.rpc('retry_notification',{job_input:job.id});setBusy(false);if(r.error)setError(r.error.message);else {setMessage(t('Повідомлення повернуто в чергу.'));await load()}}
 const statuses:Record<string,string>={queued:'У черзі',sending:'Надсилається',sent:'Прийнято провайдером',failed:'Помилка, буде повтор',uncertain:'Потрібна перевірка доставки',cancelled:'Скасовано'}
 return <section className="panel settings reminder-settings"><h2>{t('Нагадування клієнтам')}</h2>{settings&&<form className="settings" onSubmit={e=>{e.preventDefault();void save()}}>{([['email_enabled','Email-нагадування'],['reminder_24h_enabled','За 24 години до запису'],['reminder_2h_enabled','За 2 години до запису'],['repeat_enabled','Нагадування про повторний візит']] as const).map(([key,label])=><label key={key}><span>{t(label)}</span><input type="checkbox" disabled={busy} checked={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}<p>{t('Повторні візити: лише для клієнтів зі згодою в CRM. Інтервал задається окремо для кожної послуги.')}</p><button className="primary" disabled={busy}>{t('Зберегти налаштування')}</button></form>}<details><summary>{t('Інтервали повторних послуг')}</summary>{services.map(s=><form className="planning-toolbar" key={s.id} onSubmit={e=>{e.preventDefault();void interval(s.id,String(s.repeat_interval_months||''))}}><label>{s.name}<NumberInput value={s.repeat_interval_months??''} min={1} max={60} step={1} placeholder={t('Вимкнено')} onChange={e=>setServices(rows=>rows.map(r=>r.id===s.id?{...r,repeat_interval_months:e.target.value?Number(e.target.value):null}:r))}/></label><span>{t('місяців')}</span><button className="secondary" disabled={busy}>{t('Зберегти')}</button></form>)}</details>{error&&<p role="alert">{t(error)}</p>}{message&&<p role="status">{t(message)}</p>}<details><summary>{t('Журнал повідомлень')}</summary><button className="text-btn" onClick={()=>void load()}>{t('Оновити')}</button>{jobs.map(j=><article className="capacity-row" key={j.id}><b>{t(({visit_24:'За 24 години до запису',visit_2:'За 2 години до запису',return_visit:'Повторний візит',work_assigned:'Призначено роботу',work_review:'Робота на перевірці',work_approved:'Роботу підтверджено',work_returned:'Роботу повернуто'} as Record<string,string>)[j.kind]||j.kind)}</b><span>{t(j.status==='failed'&&j.attempts>=5?'Повтори вичерпано':statuses[j.status]||j.status)}</span><small>{new Date(j.created_at).toLocaleString(localeTag(),{timeZone:timezone})}</small>{['failed','uncertain'].includes(j.status)&&new Date(j.expires_at).getTime()>Date.now()&&<button className="secondary" disabled={busy} onClick={()=>void retry(j)}>{t('Повторити')}</button>}</article>)}{!jobs.length&&<p>{t('Повідомлень ще немає.')}</p>}</details></section>
}
