import { DateInput } from './components/FormInputs'
import { studioDateTime } from './lib/formValues'
import { useEffect, useMemo, useState } from 'react'

type Service = { id:string; name:string; price:number; duration_minutes:number }
type Staff = { id:string; full_name:string; specialty:string | null }
type Busy = { staff_id:string; starts_at:string; ends_at:string }
type Shift = { staff_id:string; weekday:number; starts_at:string; ends_at:string }
type Data = { studio:{name:string;address:string|null;timezone:string};services:Service[];staff:Staff[];appointments:Busy[];schedules:Shift[] }
const money=(value:number)=>new Intl.NumberFormat('uk-UA').format(value)+' ₴'
const key=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60_000).toISOString().slice(0,10)
const plusDays=(days:number)=>{const value=new Date();value.setDate(value.getDate()+days);return key(value)}

export default function PublicBookingPage({slug}:{slug:string}) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[serviceId,setServiceId]=useState(''),[staffId,setStaffId]=useState(''),[date,setDate]=useState(plusDays(1)),[time,setTime]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[car,setCar]=useState(''),[sending,setSending]=useState(false),[done,setDone]=useState(false)
  useEffect(()=>{let active=true;void fetch(`/api/public/booking?slug=${encodeURIComponent(slug)}`).then(async response=>({ok:response.ok,body:await response.json()})).then(result=>{if(!active)return;if(!result.ok){setError(result.body.error||'Студію не знайдено');return}setData(result.body);setServiceId(result.body.services[0]?.id||'');setStaffId(result.body.staff[0]?.id||'')}).catch(()=>active&&setError('Не вдалося завантажити форму. Спробуйте ще раз.')).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug])
  const service=data?.services.find(item=>item.id===serviceId)
  const slots=useMemo(()=>{if(!data||!service||!staffId||!date)return[];const weekday=new Date(`${date}T12:00:00`).getDay(),staffShifts=data.schedules.filter(item=>item.staff_id===staffId),shift=staffShifts.find(item=>item.weekday===weekday),toMinutes=(value:string)=>{const [hour,minute]=value.slice(0,5).split(':').map(Number);return hour*60+minute};if(staffShifts.length&&!shift)return[];const startLimit=shift?toMinutes(shift.starts_at):9*60,endLimit=shift?toMinutes(shift.ends_at):19*60;return Array.from({length:Math.max(0,Math.ceil((endLimit-startLimit)/30))},(_,index)=>{const total=startLimit+index*30;return `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}).filter(slot=>{const slotMinutes=toMinutes(slot),start=studioDateTime(date,slot,data.studio.timezone),end=new Date(start.getTime()+service.duration_minutes*60_000);return slotMinutes+service.duration_minutes<=endLimit&&!data.appointments.some(item=>item.staff_id===staffId&&start<new Date(item.ends_at)&&end>new Date(item.starts_at))})},[data,service,staffId,date])
  useEffect(()=>{if(!slots.includes(time))setTime(slots[0]||'')},[slots,time])
  async function submit(event:React.FormEvent){event.preventDefault();if(!service||!time)return;setSending(true);setError('');try{const response=await fetch('/api/public/booking',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,clientName:name,phone,email,car,serviceId,staffId,startsAt:studioDateTime(date,time,data?.studio.timezone).toISOString()})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не вдалося надіслати заявку');setDone(true)}catch(reason){setError(reason instanceof Error?reason.message:'Не вдалося надіслати заявку')}finally{setSending(false)}}
  if(loading)return <main className="public-page"><div className="public-card">Завантаження запису…</div></main>
  if(error&&!data)return <main className="public-page"><div className="public-card"><h1>Онлайн-запис недоступний</h1><p>{error}</p></div></main>
  if(done)return <main className="public-page"><div className="public-card"><p>{data?.studio.name}</p><h1>Заявку надіслано</h1><p>Адміністратор перевірить час. Після підтвердження ми надішлемо лист на вказаний email.</p><button className="primary" onClick={()=>{setDone(false);setName('');setPhone('');setEmail('');setCar('')}}>Створити ще одну заявку</button></div></main>
  return <main className="public-page"><form className="public-card" onSubmit={submit}><p>{data?.studio.name}</p><h1>Онлайн-запис</h1>{data?.studio.address&&<small>{data.studio.address}</small>}<label>Послуга<select value={serviceId} onChange={e=>setServiceId(e.target.value)}>{data?.services.map(item=><option key={item.id} value={item.id}>{item.name} · {item.duration_minutes} хв · {money(item.price)}</option>)}</select></label><label>Майстер<select value={staffId} onChange={e=>setStaffId(e.target.value)}>{data?.staff.map(item=><option key={item.id} value={item.id}>{item.full_name}{item.specialty?` · ${item.specialty}`:''}</option>)}</select></label><label>Дата<DateInput required type="date" min={plusDays(1)} max={plusDays(30)} value={date} onChange={e=>setDate(e.target.value)}/></label><div><b>Доступний час</b><div className="slot-list">{slots.map(slot=><button type="button" key={slot} className={slot===time?'primary':'slot'} onClick={()=>setTime(slot)}>{slot}</button>)}</div>{!slots.length&&<p>На цю дату немає доступного часу.</p>}</div><label>Ваше ім’я<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Телефон<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+380…"/></label><label>Email для підтвердження<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Автомобіль<input value={car} onChange={e=>setCar(e.target.value)} placeholder="Марка, модель, номер"/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={sending||!time||!data?.services.length||!data?.staff.length}>{sending?'Надсилаємо…':'Надіслати заявку'}</button></form></main>
}
