import {t} from './i18n/core'
import {useState,type FormEvent} from 'react'
import {Plus,Trash2} from 'lucide-react'
import {NumberInput} from './components/FormInputs'
import {Select} from './components/Select'
import {serviceOptionsError,type ServiceOptions,type ServiceVariant} from './lib/bookingAvailability'
import './service-variants.css'
export type CatalogService=[string,string,string,number]
export default function ServiceEditor({service,options,onSave,close}:{service:CatalogService|null;options?:ServiceOptions;onSave:(service:CatalogService,options:ServiceOptions)=>Promise<string|void>|void;close:()=>void}){
 const [name,setName]=useState(service?.[0]||''),[category,setCategory]=useState(service?.[1]||'Мийка'),[duration,setDuration]=useState(service?.[2]||'1 год'),[price,setPrice]=useState(String(service?.[3]??'')),[description,setDescription]=useState(options?.description||''),[variants,setVariants]=useState<ServiceVariant[]>(options?.variants||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 function change(id:string,patch:Partial<ServiceVariant>){setVariants(rows=>rows.map(v=>v.id===id?{...v,...patch}:v))}
 function add(){setVariants(rows=>[...rows,{id:crypto.randomUUID(),name:'',price:Number(price)||0,duration_minutes:60,description:''}])}
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;const details={description:description.trim(),variants:variants.map(v=>({...v,name:v.name.trim(),description:(v.description||'').trim()}))};const problem=serviceOptionsError(details);if(problem){setError(problem);return}const cheapest=[...variants].sort((a,b)=>a.price-b.price)[0];const amount=cheapest?.price??Number(price);if(!name.trim()||!Number.isFinite(amount)||amount<0){setError('Вкажіть назву та коректну ціну.');return}setBusy(true);setError('');try{const result=await onSave([name.trim(),category,cheapest?`${cheapest.duration_minutes} хв`:duration,amount],details);if(result)setError(result);else close()}catch{setError('Не вдалося зберегти послугу. Спробуйте ще раз.')}finally{setBusy(false)}}
 return <form className="panel service-editor" onSubmit={submit}><div className="service-editor-heading"><h2>{service?'Редагувати послугу':t("Нова послуга")}</h2><button type="button" className="text-btn" disabled={busy} onClick={close}>{t("Скасувати")}</button></div><fieldset disabled={busy}><div className="service-editor-grid"><label>{t("Назва послуги")}<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Наприклад, преміум мийка"/></label><label>{t("Категорія")}<Select value={category} onChange={e=>setCategory(e.target.value)}>{[...new Set(['Мийка','Полірування','Кераміка','Хімчистка','Тонування','Інше',category])].map(c=><option key={c}>{c}</option>)}</Select></label></div><label>{t("Опис послуги")}<textarea rows={3} maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Що входить у послугу та що потрібно знати клієнту"/><small>Клієнти побачать цей опис під час онлайн-запису.</small></label>
 {!variants.length&&<div className="service-editor-grid"><label>{t("Тривалість")}<input required value={duration} onChange={e=>setDuration(e.target.value)} placeholder="90 хв"/></label><label>{t("Ціна, ₴")}<NumberInput required min={0} step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label></div>}
 <div className="service-variants-heading"><div><h3>{t("Варіанти послуги")}</h3><p>Одна послуга, різні розміри авто або комплектації. Клієнт обере один варіант.</p></div><button type="button" className="text-btn" disabled={variants.length>=20} onClick={add}><Plus size={16}/>{t(" Додати варіант")}</button></div>
 {variants.map((v,i)=><section className="service-variant-editor" key={v.id}><div className="service-editor-grid"><label>{t("Назва варіанта ")}{i+1}<input required maxLength={80} value={v.name} onChange={e=>change(v.id,{name:e.target.value})} placeholder="M — седан"/></label><label>{t("Ціна варіанта ")}{i+1}, ₴<NumberInput required min={0} step="0.01" value={Number.isFinite(v.price)?v.price:''} onChange={e=>change(v.id,{price:e.target.value===''?NaN:Number(e.target.value)})}/></label><label>{t("Тривалість варіанта ")}{i+1}, хв<NumberInput required min={1} max={1440} step={1} value={Number.isFinite(v.duration_minutes)?v.duration_minutes:''} onChange={e=>change(v.id,{duration_minutes:e.target.value===''?NaN:Number(e.target.value)})}/></label><label>{t("Опис варіанта ")}{i+1}<input maxLength={500} value={v.description||''} onChange={e=>change(v.id,{description:e.target.value})} placeholder="Для седанів і компактних авто"/></label></div><button type="button" className="text-btn" onClick={()=>setVariants(rows=>rows.filter(r=>r.id!==v.id))}><Trash2 size={15}/>{t(" Видалити варіант ")}{i+1}</button></section>)}
 {!variants.length&&<p className="service-variants-hint">Наприклад: M — 600 ₴ / 60 хв, L — 800 ₴ / 75 хв, XL — 1 000 ₴ / 90 хв.</p>}
 </fieldset>{error&&<p role="alert" className="service-editor-error">{error}</p>}<button className="primary" disabled={busy}>{busy?t("Зберігаємо…"):t("Зберегти послугу")}</button></form>
}
