import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {DateInput} from './components/FormInputs'
import {addBookingDays,studioDay} from './lib/bookingAvailability'
import {t,localeTag} from './i18n/core'
import './planning.css'
export type Plan={timezone:string;schedules:{weekday:number;starts_at:string;ends_at:string}[];appointments:{id:string;starts_at:string;ends_at:string;status:string;client:string;vehicle:string;services:string}[]}
export default function StaffCalendar({staffId,timezone='Europe/Kyiv',previewData}:{staffId:string;timezone?:string;previewData?:Plan}){
 const [day,setDay]=useState(()=>studioDay(new Date(),timezone)),[week,setWeek]=useState(true),[data,setData]=useState<Plan|null>(previewData||null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[version,setVersion]=useState(0)
 const end=addBookingDays(day,week?6:0)
 useEffect(()=>{let live=true;if(previewData){setData(previewData);return}if(!supabase)return;setLoading(true);setError('');void supabase.rpc('staff_calendar',{staff_input:staffId,from_input:day,to_input:end}).then(({data,error})=>{if(!live)return;setLoading(false);if(error){setData(null);setError(t('Не вдалося завантажити календар. Спробуйте ще раз.'))}else setData(data)});return()=>{live=false}},[staffId,day,end,version,previewData])
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setVersion(v=>v+1)},30000);return()=>clearInterval(timer)},[])
 const zone=data?.timezone||timezone,format=(value:string)=>new Date(value).toLocaleTimeString(localeTag(),{timeZone:zone,hour:'2-digit',minute:'2-digit'})
 return <section className="panel staff-calendar"><h2>{t('Мій календар')}</h2><div className="planning-toolbar"><button className="secondary" onClick={()=>setDay(addBookingDays(day,week?-7:-1))} aria-label={t('Попередній період')}>←</button><DateInput required value={day} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/><button className="secondary" onClick={()=>setDay(addBookingDays(day,week?7:1))} aria-label={t('Наступний період')}>→</button><button className="text-btn" onClick={()=>setDay(studioDay(new Date(),zone))}>{t('Сьогодні')}</button><button className="secondary" aria-pressed={!week} onClick={()=>setWeek(false)}>{t('День')}</button><button className="secondary" aria-pressed={week} onClick={()=>setWeek(true)}>{t('Тиждень')}</button></div><small>{zone}</small>{loading&&<p role="status">{t('Завантажуємо календар…')}</p>}{error&&<p role="alert">{error}<button className="text-btn" onClick={()=>setVersion(v=>v+1)}>{t('Оновити')}</button></p>}<div className="planning-days">{Array.from({length:week?7:1},(_,i)=>addBookingDays(day,i)).map(date=>{const shifts=data?.schedules.filter(s=>s.weekday===new Date(date+'T12:00:00Z').getUTCDay())||[],rows=data?.appointments.filter(a=>studioDay(new Date(a.starts_at),zone)<=date&&studioDay(new Date(new Date(a.ends_at).getTime()-1),zone)>=date).sort((a,b)=>a.starts_at.localeCompare(b.starts_at))||[];return <article key={date}><h3>{new Date(date+'T12:00:00Z').toLocaleDateString(localeTag(),{timeZone:'UTC',weekday:'short',day:'numeric',month:'short'})}</h3><small>{shifts.length?shifts.map(s=>s.starts_at.slice(0,5)+'–'+s.ends_at.slice(0,5)).join(', '):t('Графік не задано')}</small>{rows.map(a=><div className="planning-booking" key={a.id}><b>{studioDay(new Date(a.starts_at),zone)<date?'00:00':format(a.starts_at)}–{studioDay(new Date(a.ends_at),zone)>date?'24:00':format(a.ends_at)}</b><strong>{a.vehicle||t('Авто не вказано')}</strong><span>{a.client}</span><span>{a.services}</span><small>{t(({pending:'Очікує підтвердження',confirmed:'Підтверджено',in_progress:'В роботі',completed:'Завершено'} as Record<string,string>)[a.status]||a.status)}</small></div>)}{!loading&&!error&&!rows.length&&<p>{t('Записів немає')}</p>}</article>})}</div></section>
}
