import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {Select} from './components/Select'
import {t} from './i18n/core'
export type Setup={name:string;address:string;phone:string;timezone:string;completed:boolean;services:number;staff:number;schedules:number}
export default function StudioSetup({tenantId,open,onSaved,previewStore}:{tenantId:string;open:(page:string)=>void;onSaved:()=>void;previewStore?:{load:()=>Setup;save:(data:Setup,complete:boolean)=>Setup}}){
 const [data,setData]=useState<Setup|null>(previewStore?.load()||null),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let alive=true;if(supabase)void supabase.rpc('studio_setup',{studio:tenantId}).then(({data,error})=>{if(alive){if(error)setError(t('Не вдалося завантажити налаштування студії.'));else setData(data)}});return()=>{alive=false}},[tenantId])
 async function save(complete=false){if(!data||busy)return;if(previewStore){setData(previewStore.save(data,complete));setStep(n=>Math.min(3,n+1));return}if(!supabase)return;setBusy(true);setError('');const r=await supabase.rpc('studio_setup',{studio:tenantId,profile_input:step===0?{name:data.name,address:data.address,phone:data.phone,timezone:data.timezone}:null,complete_input:complete});setBusy(false);if(r.error)setError(r.error.message);else {setData(r.data);setStep(n=>Math.min(3,n+1));onSaved()}}
 if(data?.completed)return null
 if(!data)return error?<p className="content" role="alert">{t(error)}</p>:null
 const titles=['Профіль студії','Послуги','Команда і графік','Готовність до запису']
 return <section className="content"><div className="panel settings"><h2>{t('Підготуйте студію до першого запису')}</h2><nav className="planning-toolbar">{titles.map((title,i)=><button type="button" className="secondary" key={title} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}. {t(title)}</button>)}</nav>{step===0?<form className="settings" onSubmit={e=>{e.preventDefault();void save()}}><label>{t('Назва студії')}<input required value={data.name} onChange={e=>setData({...data,name:e.target.value})}/></label><label>{t('Адреса')}<input required value={data.address} onChange={e=>setData({...data,address:e.target.value})}/></label><label>{t('Телефон студії')}<input required type="tel" value={data.phone} onChange={e=>setData({...data,phone:e.target.value})}/></label><label>{t('Часовий пояс')}<Select value={data.timezone} onChange={e=>setData({...data,timezone:e.target.value})}>{[...new Set([data.timezone,'Europe/Kyiv','Europe/Warsaw','Europe/Berlin','Europe/London'])].map(z=><option key={z}>{z}</option>)}</Select></label><button className="primary" disabled={busy}>{t('Зберегти й продовжити')}</button></form>:step===1?<><p>{t('Додайте послуги, ціни, тривалість і варіанти автомобілів.')}</p><p>{t('Послуг')}: {data.services}</p><button className="primary" onClick={()=>open('Послуги')}>{t('Відкрити каталог')}</button><button className="text-btn" onClick={()=>setStep(2)}>{t('Далі')}</button></>:step===2?<><p>{t('Запросіть майстрів, оберіть їхні послуги та робочі години.')}</p><p>{t('Майстрів')}: {data.staff} · {t('Робочих інтервалів')}: {data.schedules}</p><button className="primary" onClick={()=>open('Команда')}>{t('Налаштувати команду')}</button><button className="text-btn" onClick={()=>setStep(3)}>{t('Далі')}</button></>:<><p>{t('Перевірте публічну сторінку запису. Імпорт клієнтів можна виконати пізніше в налаштуваннях.')}</p><button className="secondary" onClick={()=>open('Онлайн-запис')}>{t('Відкрити онлайн-запис')}</button><button className="primary" disabled={busy} onClick={()=>void save(true)}>{t('Завершити налаштування')}</button></>}{error&&<p role="alert">{t(error)}</p>}</div></section>
}
