import {t,localeTag} from './i18n/core'
import {studioDay,addBookingDays} from './lib/bookingAvailability'
import {financeDay,type FinanceCash} from './lib/finance'
import type {WorkOrder} from './WorkOrders'
import type {Booking} from './data'
import {PostsMap,type StudioPost} from './StudioPosts'
export default function StudioOverview({orders,bookings,cash,posts,postError,timezone,financeAccess,navigate,openOrder}:{orders:WorkOrder[];bookings:Booking[];cash:FinanceCash[];posts:StudioPost[];postError:string;timezone:string;financeAccess:boolean;navigate:(page:string,filters?:Record<string,string>)=>void;openOrder:(id:string)=>void}){
 const today=studioDay(new Date(),timezone),week=addBookingDays(today,-6),money=(n:number)=>new Intl.NumberFormat(localeTag()).format(n)+' ₴',income=(from:string)=>cash.filter(c=>!c.isAccrual&&c.direction==='income'&&financeDay(c.date,timezone)>=from&&financeDay(c.date,timezone)<=today).reduce((n,c)=>n+c.amount,0)
 const active=orders.filter(o=>!['ready','issued','cancelled'].includes(o.status)),occupied=posts.filter(p=>active.some(o=>o.postId===p.id)).length,todayBookings=bookings.filter(b=>b.date===today&&!['Скасовано','Не прийшов'].includes(b.status)).sort((a,b)=>a.time.localeCompare(b.time))
 const attention=[{title:'Потрібно призначити',count:active.filter(o=>o.status==='new').length,page:'Замовлення',filter:{status:'new'}},{title:'На перевірці',count:active.filter(o=>o.status==='review').length,page:'Замовлення',filter:{status:'review'}},{title:'Термін минув',count:active.filter(o=>o.dueAt&&Date.parse(o.dueAt)<Date.now()).length,page:'Замовлення',filter:{overdue:'1'}},{title:'Онлайн-запис',count:bookings.filter(b=>b.source==='public'&&b.status==='Очікує підтвердження').length,page:'Онлайн-запис',filter:{}}]
 return <section className="content studio-overview"><div className="page-title"><div><p>{t('Студія зараз')}</p><h1>{t('Огляд')}</h1></div>{financeAccess&&<button className="text-btn" onClick={()=>navigate('Аналітика')}>{t('Уся аналітика →')}</button>}</div><div className="overview-kpis">{financeAccess&&<><button className="panel" onClick={()=>navigate('Аналітика',{from:today,to:today})}><span>{t('Надходження сьогодні')}</span><strong>{money(income(today))}</strong></button><button className="panel" onClick={()=>navigate('Аналітика',{from:week,to:today})}><span>{t('Надходження за 7 днів')}</span><strong>{money(income(week))}</strong></button></>}<button className="panel" onClick={()=>navigate('Список робіт',{post:'occupied'})}><span>{t('Зайняті пости')}</span><strong>{occupied} / {posts.length}</strong></button></div><section className="panel"><h2>{t('Потребують уваги')}</h2><div className="overview-attention">{attention.map(a=><button key={a.title} onClick={()=>navigate(a.page,a.filter as Record<string,string>)}><b>{a.count}</b><span>{t(a.title)} →</span></button>)}</div></section><PostsMap posts={posts} orders={orders} error={postError} open={openOrder} settings={()=>navigate('Пости')}/><section className="panel"><div className="panel-head"><h2>{t('Розклад на сьогодні')}</h2><button className="text-btn" onClick={()=>navigate('Календар',{date:today})}>{t('Календар')} →</button></div>{todayBookings.map(b=>{const order=orders.find(o=>o.appointmentId===String(b.id));return <button className="overview-visit" key={b.id} onClick={()=>order?openOrder(String(order.id)):navigate(b.source==='public'?'Онлайн-запис':'Календар',{date:today})}><time>{b.time}</time><span><b>{b.car||b.client}</b><small>{b.client} · {b.service}</small></span><span>{b.tech}</span></button>})}{!todayBookings.length&&<p>{t('На сьогодні записів немає')}</p>}</section></section>
}
