import {t} from './i18n/core'
import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
type Admin={user_id:string;name:string;email:string;active:boolean;finance_access:boolean;registered:boolean}
export default function StudioAdministrators({tenantId}:{tenantId:string}){
 const [items,setItems]=useState<Admin[]>([]),[name,setName]=useState(''),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){if(!supabase)return;const r=await supabase.rpc('list_studio_administrators',{studio:tenantId});if(r.error)setError('Не вдалося завантажити адміністраторів. Перевірте міграцію 035.');else setItems(r.data||[])}
 useEffect(()=>{void load()},[tenantId])
 async function send(action:string,userId?:string){if(!supabase||busy)return;setBusy(true);setError('');setMessage('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Увійдіть повторно');const r=await fetch('/api/staff/administrator',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({tenantId,name,email,action,userId})});const result=await r.json();if(!r.ok)throw new Error(result.error);setMessage(result.message);if(action==='invite'){setName('');setEmail('')}await load()}catch(e){setError(e instanceof Error?e.message:'Помилка')}finally{setBusy(false)}}
 async function change(a:Admin,patch:Partial<Admin>){if(!supabase||busy)return;setBusy(true);setError('');const r=await supabase.from('tenant_memberships').update(patch).eq('tenant_id',tenantId).eq('user_id',a.user_id).eq('role','admin').select('user_id').single();if(r.error)setError(r.error.message);else await load();setBusy(false)}
 return <section className="content"><h2>{t("Адміністратори студії")}</h2><p>Адміністратор працює із записами, клієнтами, чеками й командою. Фінансова аналітика та зарплати доступні лише з дозволу власника. Оплату тарифу й управління адміністраторами виконує власник.</p><form className="panel settings" onSubmit={e=>{e.preventDefault();void send('invite')}}><h3>{t("Запросити адміністратора")}</h3><label>{t("Ім’я")}<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("Окремий email")}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="primary" disabled={busy}>{t("Створити доступ і надіслати запрошення")}</button></form>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{items.map(a=><article className="panel settings" key={a.user_id}><h3>{a.name}</h3><p>{a.email} · {!a.active?t("Заблокований"):a.registered?t("Зареєстрований"):t("Очікує активації")}</p><label><input type="checkbox" disabled={busy} checked={a.finance_access} onChange={e=>void change(a,{finance_access:e.target.checked})}/>{t(" Доступ до фінансів та зарплат")}</label><button className="secondary" disabled={busy} onClick={()=>void change(a,{active:!a.active})}>{a.active?t("Заблокувати"):t("Активувати")}</button><button className="text-btn" disabled={busy||!a.active} onClick={()=>void send('recovery',a.user_id)}>{t("Повторний лист / відновити пароль")}</button></article>)}</section>
}
