import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
import {t,localeTag} from './i18n/core'
import './recommendations.css'
type Recommendation={id:string;kind:'return'|'timing'|'pricing'|'upsell'|'demand';evidence:Record<string,string|number>;vote:string;feedback_count:number;priority:number}
export type RecommendationFeed={recommendations:Recommendation[];readiness:{completed_orders:number;history_days:number;generated_at:string;method:string}}
const titles={return:'Перевірте повторний візит',timing:'Перегляньте тривалість послуги',pricing:'Перевірте собівартість і ціну',upsell:'Обговоріть додаткову послугу',demand:'Перевірте день із нижчим попитом'}
const advice={return:'Клієнт не повернувся у звичний строк. Перевірте історію та доречність особистого контакту. Це сигнал, а не прогноз втрати клієнта.',timing:'Роботи регулярно тривають довше плану. Перевірте складність автомобілів, перерви таймера та тривалість у каталозі.',pricing:'Більша тривалість може впливати на маржу. Спочатку перевірте витрати й обсяг робіт. Даних недостатньо для автоматичного розрахунку нової ціни.',upsell:'Ці послуги часто замовляють разом у вашій студії. Перевірте стан автомобіля й потребу клієнта перед пропозицією.',demand:'Записів менше, ніж в інші дні з історією. Перевірте графік, вихідні та доступність майстрів. Кількість записів не дорівнює завантаженню.'}
const metrics:Record<string,string>={client:'Клієнт',service:'Послуга',base_service:'Основна послуга',visits:'Візити',typical_days:'Звичний інтервал, днів',days_since:'Днів після візиту',samples:'Підтверджені роботи з таймером',planned:'План, хв',actual:'Факт, хв',together:'Спільні замовлення',base_orders:'Замовлення основної послуги',weekday:'День тижня',bookings:'Записи',average:'Середня кількість записів за день тижня',weeks:'Тижні з записами'}
export default function StudioRecommendations({tenantId,preview}:{tenantId?:string|null;preview?:RecommendationFeed}){
 const [feed,setFeed]=useState<RecommendationFeed|null>(null),[busy,setBusy]=useState(false),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState(''),[version,setVersion]=useState(0),[reviewed,setReviewed]=useState(false)
 useEffect(()=>{let live=true;setError('');setFeed(null);if(import.meta.env.DEV&&preview){setFeed(structuredClone(preview));return}if(!tenantId||!supabase){setError(t('Для рекомендацій підключіть студію.'));return}setBusy(true);void Promise.resolve(supabase.rpc('studio_recommendation_feed',{studio:tenantId})).then(r=>{if(!live)return;setBusy(false);if(r.error)setError(t('Не вдалося оновити рекомендації'));else setFeed(r.data as RecommendationFeed)}).catch(()=>{if(live){setBusy(false);setError(t('Не вдалося оновити рекомендації'))}});return()=>{live=false}},[tenantId,version,preview])
 async function rate(id:string,vote:string){if(saving)return;setSaving(id);setError('');try{if(!(import.meta.env.DEV&&preview)){if(!supabase)throw Error();const r=await supabase.rpc('rate_studio_recommendation',{recommendation:id,rating:vote});if(r.error)throw r.error}setFeed(f=>f?{...f,recommendations:f.recommendations.map(r=>r.id===id?{...r,vote}:r)}:f)}catch{setError(t('Не вдалося зберегти оцінку'))}finally{setSaving(null)}}
 const rows=feed?.recommendations.filter(r=>reviewed||r.vote==='none')||[]
 return <section className="studio-recommendations"><header className="page-title"><div><h2>{t('Рекомендації')}</h2><p>{t('Підказки з історії вашої студії')}</p></div><button className="secondary" disabled={busy||!!saving} onClick={()=>setVersion(v=>v+1)}>{t('Оновити рекомендації')}</button></header><div className="panel"><b>{t('Адаптивні правила · без зовнішнього AI')}</b><p>{t('Нові роботи оновлюють розрахунки. Оцінки коригують пріоритет типів підказок після п’яти різних оцінених рекомендацій. Це не навчання мовної моделі й не гарантія результату.')}</p><p>{t('Ціни, записи та повідомлення не змінюються автоматично. Дані інших студій не використовуються.')}</p>{feed&&<small>{t('Завершені замовлення')}: {feed.readiness.completed_orders} · {t('Днів історії')}: {feed.readiness.history_days} · {t('Оновлено')}: {new Date(feed.readiness.generated_at).toLocaleString(localeTag())}</small>}</div><details className="panel"><summary>{t('Коли з’являються рекомендації')}</summary><p>{t('Повторний візит: щонайменше три візити та два інтервали від доби. Затримки: п’ять робіт із планом і таймером за 90 днів. Перевірка ціни: дванадцять таких робіт. Додаткова послуга: п’ять спільних замовлень і частка від 35%. Попит: від 40 записів і восьми тижнів спостережень.')}</p><p>{t('Оцінка спільна для студії: повторне натискання замінює її, а не додає голос. Можна скасувати оцінку. Позначка «Виконано» не підтверджує фінансовий результат.')}</p></details><label className="recommendation-toggle"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>{t('Показувати оцінені підказки')}</label>{busy&&<p role="status">{t('Завантаження…')}</p>}{error&&<p role="alert" className="wf-error">{error}</p>}<div className="recommendation-grid">{rows.map(r=><article className="panel" key={r.id}><small>{t('Сигнал для перевірки')}</small><h3>{t(titles[r.kind])}</h3><p>{t(advice[r.kind])}</p><dl>{Object.entries(r.evidence).map(([key,value])=><div key={key}><dt>{t(metrics[key]||key)}</dt><dd>{key==='weekday'?t(['','Пн','Вт','Ср','Чт','Пт','Сб','Нд'][Number(value)]||'—'):String(value)}</dd></div>)}</dl><small>{r.feedback_count>=5?t('Пріоритет враховує оцінки студії'):t('Базовий пріоритет: ще мало оцінок')}</small>{r.vote!=='none'&&<p>{t(({useful:'Корисно',not_useful:'Не корисно',done:'Виконано'} as Record<string,string>)[r.vote])}</p>}<div className="wf-actions">{[['useful','Корисно'],['not_useful','Не корисно'],['done','Виконано'],...(r.vote!=='none'?[['none','Скасувати оцінку']]:[])].map(([vote,label])=><button key={vote} className="text-btn" disabled={!!saving} aria-pressed={r.vote===vote} onClick={()=>void rate(r.id,vote)}>{t(label)}</button>)}</div></article>)}</div>{feed&&!rows.length&&<p className="panel">{t('Нових підказок поки немає. Потрібно більше історії або відхилень від звичного процесу; відсутність підказок не означає помилку.')}</p>}</section>
}
