import { useEffect, useState } from 'react'
import { Ban, CheckCircle2, Copy, KeyRound, RotateCw } from 'lucide-react'
import { supabase } from './lib/supabase'

type AccessStaff={id:string;fullName:string;specialty:string;active:boolean;userId:string|null;inviteCode:string|null}
const makeCode=()=>Math.random().toString(36).slice(2,10).toUpperCase()

export default function TeamAccess(){
  const [staff,setStaff]=useState<AccessStaff[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState<string|null>(null)
  useEffect(()=>{if(!supabase)return;void (async()=>{const membership=await supabase.from('tenant_memberships').select('tenant_id').limit(1).maybeSingle();if(!membership.data)return;const {data,error}=await supabase.from('staff_profiles').select('id,full_name,specialty,active,user_id,invite_code').eq('tenant_id',membership.data.tenant_id).order('full_name');if(error){setMessage('Не вдалося завантажити доступи майстрів.');return}setStaff((data||[]).map(item=>({id:item.id,fullName:item.full_name,specialty:item.specialty||'Майстер',active:item.active,userId:item.user_id,inviteCode:item.invite_code})))})()},[])
  async function update(member:AccessStaff,patch:Partial<AccessStaff>){if(!supabase)return;setBusy(member.id);const payload:{active?:boolean;invite_code?:string|null}={};if(patch.active!==undefined)payload.active=patch.active;if(patch.inviteCode!==undefined)payload.invite_code=patch.inviteCode;const {error}=await supabase.from('staff_profiles').update(payload).eq('id',member.id);setBusy(null);if(error){setMessage('Не вдалося змінити доступ.');return}setStaff(list=>list.map(item=>item.id===member.id?{...item,...patch}:item));setMessage(patch.active===false?'Доступ майстра заблоковано.':patch.active===true?'Доступ майстра активовано.':'Новий код активації створено.')}
  async function copy(code:string){try{await navigator.clipboard.writeText(code);setMessage('Код скопійовано. Передайте його майстру.')}catch{setMessage(`Код активації: ${code}`)}}
  if(!staff.length)return null
  return <section className="content team-access"><div className="page-title"><div><p>Кабінет майстра</p><h1>Доступи команди</h1></div></div><div className="panel access-intro"><KeyRound size={21}/><p>Створіть код для майстра. Він реєструється у сервісі, відкриває «Кабінет майстра» та вводить код один раз. Заблокований майстер одразу втрачає доступ до змін, завдань і нарахувань.</p></div>{message&&<p className="task-message" role="status">{message}</p>}<div className="access-list">{staff.map(member=>{const inactive=!member.active;const unlinked=!member.userId;return <article className="panel access-row" key={member.id}><div><b>{member.fullName}</b><small>{member.specialty}</small></div><span className={inactive?'access-state blocked':'access-state'}>{inactive?'Заблоковано':member.userId?'Акаунт активовано':'Очікує активації'}</span>{unlinked&&member.active&&<div className="invite-code"><code>{member.inviteCode||'—'}</code><button className="icon-btn" aria-label="Скопіювати код" onClick={()=>member.inviteCode&&void copy(member.inviteCode)}><Copy size={16}/></button><button className="icon-btn" aria-label="Оновити код" onClick={()=>void update(member,{inviteCode:makeCode()})}><RotateCw size={16}/></button></div>}<button className={inactive?'primary':'danger-btn'} disabled={busy===member.id} onClick={()=>void update(member,{active:inactive})}>{inactive?<><CheckCircle2 size={16}/> Активувати</>:<><Ban size={16}/> Заблокувати</>}</button></article>})}</div></section>
}
