import { useEffect, useMemo, useState } from 'react'
import { CircleDollarSign, Save } from 'lucide-react'
import { supabase } from './lib/supabase'

type Staff={id:string|number;name:string;color:string;compensationPercent?:number|null;hourlyRate?:number}
type Service={id:string;name:string;category:string;price:number}
type Rate={id:string;staffId:string;serviceId:string;percent:number|null;fixedAmount:number|null}
const money=(value:number)=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:2}).format(value)+' ₴'

export default function TeamCompensation({staff}:{staff:Staff[]}){
  const [tenantId,setTenantId]=useState<string|null>(null),[services,setServices]=useState<Service[]>([]),[rates,setRates]=useState<Rate[]>([]),[staffId,setStaffId]=useState(''),[basePercent,setBasePercent]=useState(''),[hourlyRate,setHourlyRate]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false)
  const current=staff.find(item=>String(item.id)===staffId)
  useEffect(()=>{if(!staffId&&staff[0])setStaffId(String(staff[0].id))},[staff,staffId])
  useEffect(()=>{if(!current)return;setBasePercent(current.compensationPercent===null||current.compensationPercent===undefined?'':String(current.compensationPercent));setHourlyRate(current.hourlyRate?String(current.hourlyRate):'')},[current?.id,current?.compensationPercent,current?.hourlyRate])
  useEffect(()=>{if(!supabase)return;void supabase.auth.getUser().then(async({data})=>{if(!data.user)return;const membership=await supabase.from('tenant_memberships').select('tenant_id').limit(1).maybeSingle();if(!membership.data)return;setTenantId(membership.data.tenant_id);const [catalog,compensation]=await Promise.all([supabase.from('services').select('id,name,category,price').eq('tenant_id',membership.data.tenant_id).eq('active',true).order('name'),supabase.from('staff_service_compensation').select('id,staff_id,service_id,percent,fixed_amount').eq('tenant_id',membership.data.tenant_id)]);if(catalog.data)setServices(catalog.data.map(item=>({id:item.id,name:item.name,category:item.category,price:Number(item.price)})));if(compensation.data)setRates(compensation.data.map(item=>({id:item.id,staffId:item.staff_id,serviceId:item.service_id,percent:item.percent===null?null:Number(item.percent),fixedAmount:item.fixed_amount===null?null:Number(item.fixed_amount)})))})},[])
  const currentRates=useMemo(()=>rates.filter(rate=>rate.staffId===staffId),[rates,staffId])
  async function saveBase(){if(!current||!supabase||typeof current.id!=='string')return;const percent=basePercent===''?null:Number(basePercent),hourly=hourlyRate===''?0:Number(hourlyRate);if((percent!==null&&(percent<0||percent>100))||hourly<0){setMessage('Перевірте відсоток і ставку.');return}setSaving(true);const {error}=await supabase.from('staff_profiles').update({compensation_percent:percent,hourly_rate:hourly}).eq('id',current.id);setSaving(false);setMessage(error?'Не вдалося зберегти базові умови.':'Базові умови збережено. Вони застосуються до нових замовлень без індивідуального правила.')}
  async function saveRate(service:Service,percentValue:string,fixedValue:string){if(!supabase||!tenantId||!staffId){return}const percent=percentValue===''?null:Number(percentValue),fixed=fixedValue===''?null:Number(fixedValue);if(percent===null&&fixed===null){const currentRate=currentRates.find(rate=>rate.serviceId===service.id);if(currentRate)await supabase.from('staff_service_compensation').delete().eq('id',currentRate.id);setRates(list=>list.filter(rate=>rate.serviceId!==service.id||rate.staffId!==staffId));setMessage(`Для «${service.name}» використовується базовий відсоток.`);return}if((percent!==null&&(percent<0||percent>100))||(fixed!==null&&fixed<0)){setMessage('Вкажіть відсоток від 0 до 100 або додатну фіксовану суму.');return}setSaving(true);const {data,error}=await supabase.from('staff_service_compensation').upsert({tenant_id:tenantId,staff_id:staffId,service_id:service.id,percent,fixed_amount:fixed},{onConflict:'staff_id,service_id'}).select('id,staff_id,service_id,percent,fixed_amount').single();setSaving(false);if(error||!data){setMessage('Не вдалося зберегти правило.');return}const saved={id:data.id,staffId:data.staff_id,serviceId:data.service_id,percent:data.percent===null?null:Number(data.percent),fixedAmount:data.fixed_amount===null?null:Number(data.fixed_amount)};setRates(list=>[...list.filter(rate=>rate.staffId!==staffId||rate.serviceId!==service.id),saved]);setMessage(`Умови для «${service.name}» збережено.`)}
  if(!staff.length)return null
  return <section className="content team-compensation"><div className="page-title"><div><p>Оплата роботи майстрів</p><h1>Ставки та процентовка</h1></div></div><div className="panel compensation-intro"><CircleDollarSign size={21}/><p>Базовий відсоток застосовується до всіх нових замовлень майстра. Нижче можна задати окрему ставку для конкретної послуги. Фіксована сума має пріоритет над відсотком.</p></div><div className="panel compensation-base"><label>Майстер<select value={staffId} onChange={event=>setStaffId(event.target.value)}>{staff.map(item=><option key={String(item.id)} value={String(item.id)}>{item.name}</option>)}</select></label><label>Базовий відсоток, %<input min="0" max="100" step="0.01" type="number" value={basePercent} onChange={event=>setBasePercent(event.target.value)} placeholder="Наприклад, 30"/></label><label>Погодинна ставка, ₴<input min="0" step="0.01" type="number" value={hourlyRate} onChange={event=>setHourlyRate(event.target.value)} placeholder="Необов’язково"/></label><button className="primary" disabled={saving} onClick={()=>void saveBase()}><Save size={16}/> Зберегти</button></div>{message&&<p className="task-message" role="status">{message}</p>}<div className="panel compensation-table"><div className="compensation-row compensation-head"><span>Послуга</span><span>Ціна для клієнта</span><span>Відсоток майстра</span><span>Або фіксовано, ₴</span></div>{services.map(service=>{const rate=currentRates.find(item=>item.serviceId===service.id);return <RateRow key={service.id} service={service} rate={rate} save={saveRate}/>} )}{!services.length&&<p className="empty-state">Додайте послуги до каталогу, щоб налаштувати оплату майстрів.</p>}</div></section>
}
function RateRow({service,rate,save}:{service:Service;rate:Rate|undefined;save:(service:Service,percent:string,fixed:string)=>Promise<void>}){const [percent,setPercent]=useState(rate?.percent===null||rate?.percent===undefined?'':String(rate.percent)),[fixed,setFixed]=useState(rate?.fixedAmount===null||rate?.fixedAmount===undefined?'':String(rate.fixedAmount));useEffect(()=>{setPercent(rate?.percent===null||rate?.percent===undefined?'':String(rate.percent));setFixed(rate?.fixedAmount===null||rate?.fixedAmount===undefined?'':String(rate.fixedAmount))},[rate?.id,rate?.percent,rate?.fixedAmount]);return <div className="compensation-row"><span><b>{service.name}</b><small>{service.category}</small></span><span>{money(service.price)}</span><span><input min="0" max="100" step="0.01" type="number" value={percent} onChange={event=>setPercent(event.target.value)} placeholder="Базовий"/></span><span className="compensation-fixed"><input min="0" step="0.01" type="number" value={fixed} onChange={event=>setFixed(event.target.value)} placeholder="Не задано"/><button className="text-btn" onClick={()=>void save(service,percent,fixed)}>Зберегти</button></span></div>}
