import { FormEvent, useMemo, useState } from 'react'
import { CalendarClock, Plus, Trash2 } from 'lucide-react'
import TeamCompensation from './TeamCompensation'
import TeamAccess from './TeamAccess'

type Staff={id:string|number;name:string;color:string}
type Schedule={id:string|number;staffId:string|number;weekday:number;startsAt:string;endsAt:string}
const days=['Неділя','Понеділок','Вівторок','Середа','Четвер','П’ятниця','Субота']

export default function TeamSchedules({staff,schedules,save,remove}:{staff:Staff[];schedules:Schedule[];save:(item:Omit<Schedule,'id'>)=>Promise<string>;remove:(id:Schedule['id'])=>Promise<string>}){
  const [open,setOpen]=useState(false),[staffId,setStaffId]=useState(''),[weekday,setWeekday]=useState('1'),[startsAt,setStartsAt]=useState('09:00'),[endsAt,setEndsAt]=useState('18:00'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  const grouped=useMemo(()=>staff.map(member=>({member,rows:schedules.filter(row=>String(row.staffId)===String(member.id)).sort((a,b)=>a.weekday-b.weekday)})),[staff,schedules])
  async function submit(event:FormEvent){event.preventDefault();const member=staff.find(item=>String(item.id)===staffId);if(!member){setMessage('Оберіть майстра.');return}setBusy(true);const error=await save({staffId:member.id,weekday:Number(weekday),startsAt,endsAt});setBusy(false);setMessage(error||'Зміну збережено.');if(!error){setStaffId('');setOpen(false)}}
  async function deleteRow(id:Schedule['id']){if(!window.confirm('Видалити цю зміну?'))return;setMessage((await remove(id))||'Зміну видалено.')}
  return <><section className="content team-schedules"><div className="page-title"><div><p>Планування змін</p><h1>Графік команди</h1></div><button className="primary" onClick={()=>setOpen(value=>!value)}><Plus size={18}/> Додати зміну</button></div><div className="panel schedule-hint"><CalendarClock size={20}/><p>Графік допомагає планувати завантаження. Фактичний вихід майстер відзначає сам у своєму кабінеті.</p></div>{open&&<form className="panel schedule-form" onSubmit={submit}><h2>Робоча зміна</h2><label>Майстер<select required value={staffId} onChange={event=>setStaffId(event.target.value)}><option value="">Оберіть майстра</option>{staff.map(member=><option key={member.id} value={String(member.id)}>{member.name}</option>)}</select></label><label>День<select value={weekday} onChange={event=>setWeekday(event.target.value)}>{days.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></label><label>Початок<input required type="time" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>Завершення<input required type="time" value={endsAt} onChange={event=>setEndsAt(event.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Зберігаємо…':'Зберегти'}</button></form>}{message&&<p className="task-message" role="status">{message}</p>}<div className="schedule-team-grid">{grouped.map(({member,rows})=><article className="panel schedule-member" key={member.id}><header><span className="team-avatar" style={{background:member.color}}>{member.name.split(' ').map(part=>part[0]).join('').slice(0,2)}</span><div><h2>{member.name}</h2><small>{rows.length?`${rows.length} робочих днів`:'Графік ще не задано'}</small></div></header><div className="schedule-days">{rows.map(row=><div key={row.id}><b>{days[row.weekday]}</b><span>{row.startsAt}–{row.endsAt}</span><button className="text-btn" aria-label="Видалити зміну" onClick={()=>void deleteRow(row.id)}><Trash2 size={15}/></button></div>)}{!rows.length&&<p>Додайте першу зміну.</p>}</div></article>)}</div></section><TeamAccess/><TeamCompensation staff={staff}/></>
}
