import {t} from './i18n/core'
import {useEffect,useState} from 'react'
import {supabase} from './lib/supabase'
type Member={id:string;full_name:string;all_services:boolean;staff_services:{service_id:string}[]}
export default function TeamSkills({tenantId,rosterKey,catalogKey,onSaved}:{tenantId:string|null;rosterKey:string;catalogKey:string;onSaved:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[services,setServices]=useState<{id:string;name:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;if(!supabase||!tenantId)return;void Promise.all([supabase.from('staff_profiles').select('id,full_name,all_services,staff_services(service_id)').eq('tenant_id',tenantId).eq('active',true),supabase.from('services').select('id,name').eq('tenant_id',tenantId).eq('active',true)]).then(([a,b])=>{if(!active)return;if(a.error||b.error){setError('Не вдалося завантажити спеціалізації. Потрібне оновлення бази 033.');return}setMembers(a.data||[]);setServices(b.data||[])});return()=>{active=false}},[tenantId,rosterKey,catalogKey])
 function update(id:string,patch:Partial<Member>){setMembers(rows=>rows.map(p=>p.id===id?{...p,...patch}:p));setMessage('')}
 async function save(p:Member){if(!supabase||busy)return;setBusy(p.id);setError('');const r=await supabase.rpc('set_staff_services',{staff_input:p.id,all_input:p.all_services,services_input:p.staff_services.map(s=>s.service_id)});setBusy('');if(r.error)setError(r.error.message);else {setMessage(t('Спеціалізацію збережено. Вона враховується під час запису й призначення робіт.'));onSaved()}}
 return <section className="content"><h2>{t("Послуги майстрів")}</h2><p>Оберіть, які послуги виконує кожен майстер. Якщо вибрати «Лише обрані» та не позначити послуг, нові роботи з каталогу цьому майстру не призначатимуться.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<div className="team-grid">{members.map(p=><form className="panel settings" key={p.id} onSubmit={e=>{e.preventDefault();void save(p)}}><h3>{p.full_name}</h3><label><input type="checkbox" disabled={!!busy} checked={p.all_services} onChange={e=>update(p.id,{all_services:e.target.checked})}/>{t(" Усі послуги, включно з новими")}</label>{!p.all_services&&<fieldset><legend>{t("Лише обрані послуги")}</legend>{services.map(s=><label key={s.id}><input type="checkbox" checked={p.staff_services.some(x=>x.service_id===s.id)} onChange={e=>update(p.id,{staff_services:e.target.checked?[...p.staff_services,{service_id:s.id}]:p.staff_services.filter(x=>x.service_id!==s.id)})}/>{s.name}</label>)}</fieldset>}<button className="primary" disabled={!!busy}>{busy===p.id?t("Зберігаємо…"):t("Зберегти спеціалізацію")}</button></form>)}</div></section>
}
