import {t} from './i18n/core'
import { useEffect, useState } from 'react'
import { Ban, CheckCircle2 } from 'lucide-react'
import { authErrorMessage } from './lib/authMessages'
import { supabase } from './lib/supabase'

type Member={id:string;name:string;specialty:string;active:boolean;userId:string|null;inviteEmail:string|null;inviteSentAt:string|null;inviteAcceptedAt:string|null}

export default function TeamAccess({refreshVersion,tenantId}:{refreshVersion:number;tenantId:string}){
  const [members,setMembers]=useState<Member[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState<string|null>(null)
  const [emails,setEmails]=useState<Record<string,string>>({}),[sent,setSent]=useState<Record<string,number>>({})
  async function send(member:Member,action:'invite'|'resend'|'recovery'){
    if(!supabase||busy)return
    setBusy(member.id);setMessage('')
    try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Увійдіть повторно.');const response=await fetch('/api/staff/invite',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({staffId:member.id,action,email:member.userId?undefined:(emails[member.id]||member.inviteEmail||'').trim()})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Не вдалося надіслати лист.');setMessage(result.message);setSent(v=>({...v,[member.id]:Date.now()}));setReload(v=>v+1)}catch(e){setMessage(authErrorMessage({message:e instanceof Error?e.message:'Не вдалося надіслати лист.'}))}finally{setBusy(null)}
  }
  const [reload,setReload]=useState(0),[now,setNow]=useState(Date.now())
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[])
  useEffect(()=>{if(!supabase)return;void (async()=>{const {data,error}=await supabase.from('staff_profiles').select('id,full_name,specialty,active,user_id,invite_email,invite_sent_at,invite_accepted_at').eq('tenant_id',tenantId).order('full_name');if(error){setMessage('Не вдалося завантажити доступи.');return}setMembers((data||[]).map(row=>({id:row.id,name:row.full_name,specialty:row.specialty||'Майстер',active:row.active,userId:row.user_id,inviteEmail:row.invite_email,inviteSentAt:row.invite_sent_at,inviteAcceptedAt:row.invite_accepted_at})))})()},[tenantId,refreshVersion,reload])
  async function toggle(member:Member){if(!supabase||busy)return;setBusy(member.id);const active=!member.active;const {error}=await supabase.from('staff_profiles').update({active}).eq('id',member.id);setBusy(null);if(error){setMessage('Не вдалося змінити доступ.');return}setMembers(list=>list.map(item=>item.id===member.id?{...item,active}:item));setMessage(active?'Доступ майстра активовано.':'Доступ майстра заблоковано.')}
  if(!members.length)return null
  return <section className="content team-access"><div className="page-title"><div><p>Адміністрування</p><h1>{t("Доступ до кабінету майстра")}</h1></div></div>{message&&<p className="task-message" role="status">{message}</p>}<div className="access-list">{members.map(member=>{const state=!member.active?['Доступ заблоковано','blocked']:member.inviteAcceptedAt?['Майстер зареєстрований','']:member.inviteSentAt?['Запрошення надіслано — очікуємо реєстрацію','']:['Запрошення ще не надіслано','pending'];return <article className="panel access-row" key={member.id}><div><b>{member.name}</b><small>{member.specialty}{member.inviteEmail?` · ${member.inviteEmail}`:''}</small></div><span className={`access-state ${state[1]}`}>{state[0]}</span><button className={member.active?'danger-btn':'primary'} disabled={!!busy} onClick={()=>void toggle(member)}>{member.active?<><Ban size={16}/>{t(" Заблокувати")}</>:<><CheckCircle2 size={16}/>{t(" Активувати")}</>}</button><div className="staff-mail-actions">{!member.userId&&<label>{t("Email для запрошення")}<input type="email" autoComplete="off" value={emails[member.id]??member.inviteEmail??''} onChange={e=>setEmails(v=>({...v,[member.id]:e.target.value}))} placeholder="master@example.com"/></label>}<div><button className="secondary" disabled={!!busy||!member.active||now-(sent[member.id]||0)<60000} onClick={()=>void send(member,member.userId?'resend':'invite')}>{member.userId||member.inviteSentAt?'Надіслати лист повторно':'Надіслати запрошення'}</button>{member.userId&&<button className="secondary" disabled={!!busy||!member.active||now-(sent[member.id]||0)<60000} onClick={()=>void send(member,'recovery')}>{t("Відновити пароль")}</button>}</div><small>{now-(sent[member.id]||0)<60000?'Наступний лист можна запросити через хвилину.':member.userId?'Повторний лист містить посилання для створення нового пароля. Поточний пароль не зміниться до підтвердження майстром.':'Майстер отримає посилання для активації свого кабінету.'}</small></div></article>})}</div></section>
}
