import {useMemo,useState} from 'react'
import StaffCalendar,{type Plan} from '../StaffCalendar'
import StudioLoad from '../StudioLoad'
import StudioSetup,{type Setup} from '../StudioSetup'
import SupportStudios,{type Studio} from '../SupportStudios'
import {studioDay,addBookingDays} from '../lib/bookingAvailability'
import {studioDateTime} from '../lib/formValues'
import {seedBookings} from '../data'
export default function PlanningPreview(){
 const [tab,setTab]=useState('calendar'),[message,setMessage]=useState('');const timezone='Europe/Kyiv',day=studioDay(new Date(),timezone),weekday=new Date(day+'T12:00:00Z').getUTCDay()
 const stores=useMemo(()=>{let setup:Setup={name:'Test Studio',address:'',phone:'',timezone,completed:false,services:3,staff:2,schedules:5};let studios:Studio[]=[{id:'studio-test',name:'Test Studio',slug:'test',email:'test@example.com',phone:'+380000000000',timezone,plan:'start',status:'trialing',trial_ends_at:new Date(Date.now()+864000000).toISOString(),current_period_end:null,staff_count:2,client_count:15}];return {setup:{load:()=>setup,save:(value:Setup,complete:boolean)=>setup={...value,completed:complete}},support:{load:()=>studios,save:(id:string,plan:string,status:string,end:string,note:string)=>{studios=studios.map(s=>s.id===id?{...s,plan,status,current_period_end:end?studioDateTime(end,'23:59',timezone).toISOString():null}:s);setMessage(note)}}}},[])
 const plan:Plan={timezone,schedules:Array.from({length:7},(_,weekday)=>({weekday,starts_at:'09:00',ends_at:'18:00'})),appointments:[{id:'booking-test',starts_at:studioDateTime(day,'10:00',timezone).toISOString(),ends_at:studioDateTime(day,'12:30',timezone).toISOString(),client:'Тестовий клієнт',vehicle:'Mercedes-Benz GLE · TEST 001',services:'Полірування та захисне покриття',status:'confirmed'},{id:'overnight-test',starts_at:studioDateTime(addBookingDays(day,1),'16:00',timezone).toISOString(),ends_at:studioDateTime(addBookingDays(day,2),'11:00',timezone).toISOString(),client:'Тестовий клієнт',vehicle:'BMW X5 · TEST 002',services:'Кераміка',status:'in_progress'}]}
 return <div className="content"><nav className="planning-toolbar">{[['calendar','Календар майстра'],['load','Завантаження'],['setup','Підключення студії'],['support','Студії підтримки']].map(([id,name])=><button key={id} className="secondary" onClick={()=>setTab(id)}>{name}</button>)}</nav>{message&&<p role="status">{message}</p>}{tab==='calendar'&&<StaffCalendar staffId="staff-test" previewData={plan}/>} {tab==='load'&&<StudioLoad timezone={timezone} staff={[{id:'staff-test',name:'Тестовий майстер'},{id:'staff-no-schedule',name:'Без графіка'}]} schedules={[{staffId:'staff-test',weekday,startsAt:'09:00',endsAt:'18:00'}]} bookings={[{...seedBookings[0],date:day,time:'10:00',durationMinutes:150,staffId:'staff-test',startsAt:plan.appointments[0].starts_at,endsAt:plan.appointments[0].ends_at}]}/>} {tab==='setup'&&<StudioSetup tenantId="test" previewStore={stores.setup} open={setMessage} onSaved={()=>{}}/>} {tab==='support'&&<SupportStudios previewStore={stores.support}/>}</div>
}
