import { useRef, useState } from 'react'
import { MasterWorkspace, OrderWorkDialog, OwnerToday, Payroll } from '../workflow/WorkflowUI'
import { emptyData, estimate, secondsWorked, type Job, type WorkflowData } from '../workflow/model'
import type { WorkflowController } from '../workflow/useWorkflow'
import type { WorkOrder } from '../WorkOrders'

// Local visual fixture only. RPC rules, RLS and accounting are exercised against PostgreSQL in workflow-db.test.mjs.
const staff=[{id:'ruslan',name:'Руслан Тестовий',speciality:'Мийка та полірування',compensationPercent:30},{id:'armen',name:'Армен Тестовий',speciality:'Захисні покриття',compensationPercent:25}]
const now=()=>new Date().toISOString()
const initialJob:Job={id:'wash',tenant_id:'qa',work_order_id:'car-one',staff_id:null,service_id:'wash',title:'Підготовча мийка',stage:'Підготовка',position:0,status:'new',price:1000,pay_mode:'percent',rate:30,checklist:[{id:'body',title:'Очистити кузов і колісні арки',done:false},{id:'dry',title:'Висушити та перевірити покриття',done:false}],attachments:[],note:'',review_note:'',worked_seconds:0,running_since:null,submitted_at:null,approved_at:null,approved_by:null,version:1,created_at:now(),updated_at:now()}
const seed=():WorkflowData=>({...structuredClone(emptyData),jobs:[structuredClone(initialJob)],services:[{id:'wash',name:'Підготовча мийка',price:1000},{id:'polish',name:'Полірування кузова',price:3500}]})
export default function WorkflowPreview(){
 const [data,setData]=useState(seed),ref=useRef(data),[role,setRole]=useState('owner'),[selected,setSelected]=useState<string|null>(null)
 function commit(next:WorkflowData){ref.current=next;setData(next)}
 function mutation(fn:(d:WorkflowData)=>void){const next=structuredClone(ref.current);fn(next);commit(next)}
 const jobs=data.jobs,status:WorkOrder['status']=jobs.every(j=>j.status==='approved')?'ready':jobs.some(j=>j.status==='review')?'review':jobs.some(j=>j.status==='in_progress')?'in_progress':jobs.some(j=>!j.staff_id)?'new':'assigned'
 const orders:WorkOrder[]=[{id:'car-one',clientId:'client',clientName:'Олександр · тестовий клієнт',staffId:jobs[0]?.staff_id||null,staffName:'',title:'Детейлінг автомобіля',vehicle:'Mazda CX-5 · AA 1234 AA · 2022',serviceSummary:jobs.map(j=>j.title).join(', '),status,total:jobs.reduce((v,j)=>v+j.price,0),deposit:0,dueAt:'2026-09-30T18:00',notes:'Червоний кузов. Перевірити задній бампер перед нанесенням покриття.',createdAt:initialJob.created_at,statusChangedAt:now(),checklist:[],compensationPercent:null,compensationFixed:null,submittedForReviewAt:'',reviewNote:''}]
 const visible=role==='owner'||role==='payroll'?data:{...data,jobs:data.jobs.filter(j=>j.staff_id===role),shifts:data.shifts.filter(s=>s.staff_id===role),earnings:data.earnings.filter(e=>e.staff_id===role)}
 const workflow:WorkflowController={data:visible,available:true,loading:false,error:'',refresh:()=>{},
 async save(order,input,version){mutation(d=>{let job=d.jobs.find(j=>j.id===input.id);if(job&&job.version!==version)throw new Error('Дані змінилися');const mode=input.pay_mode==='auto'?'percent':input.pay_mode as Job['pay_mode'];const patch={title:String(input.title),stage:String(input.stage),position:Number(input.position),staff_id:String(input.staff_id)||null,service_id:String(input.service_id)||null,price:Number(input.price),pay_mode:mode,rate:input.pay_mode==='auto'?30:Number(input.rate),checklist:(input.checklist as {title:string}[]).map(c=>({...c,id:crypto.randomUUID(),done:false})),status:(input.staff_id?'assigned':'new') as Job['status']};if(job)Object.assign(job,patch,{version:job.version+1});else d.jobs.push({...structuredClone(initialJob),...patch,id:crypto.randomUUID(),work_order_id:order})})},
 async act(input,action,payload={}){mutation(d=>{const j=d.jobs.find(j=>j.id===input.id)!;if(j.version!==input.version)throw new Error('Дані змінилися');const sh=d.shifts.find(s=>s.staff_id===j.staff_id&&!s.ended_at);if(['start','check','submit'].includes(action)&&(!sh||sh.paused_at))throw new Error('Спочатку почніть зміну');if(action==='start'){if(d.jobs.some(x=>x.position<j.position&&x.status!=='approved'))throw new Error('Попередній етап має пройти перевірку');j.status='in_progress';j.running_since=now()}if(action==='check')j.checklist=j.checklist.map(c=>c.id===payload.item_id?{...c,done:!!payload.done}:c);if(action==='pause'||action==='submit'){j.worked_seconds=secondsWorked(j);j.running_since=null;j.status=action==='pause'?'waiting':'review';if(action==='submit')j.submitted_at=now()}if(action==='return'){j.status='waiting';j.review_note=String(payload.note);j.checklist=j.checklist.map(c=>({...c,done:false}))}if(action==='approve'){if(j.status!=='review')return;j.status='approved';j.approved_at=now();d.earnings.push({id:crypto.randomUUID(),staff_id:j.staff_id!,work_order_id:j.work_order_id,job_id:j.id,amount:estimate(j),paid_amount:0,status:'accrued',accrued_at:now(),calculation:{}})}if(action==='note')j.note=String(payload.note);if(action==='delete'){if(d.jobs.length===1)throw new Error('Залиште хоча б одну роботу');d.jobs=d.jobs.filter(x=>x.id!==j.id)}j.version++;d.events.push({id:crypto.randomUUID(),job_id:j.id,actor_id:role,event:action,detail:payload,created_at:now()})})},
 async shift(id,action){mutation(d=>{const sh=d.shifts.find(s=>s.staff_id===id&&!s.ended_at);if(action==='start'){if(!sh)d.shifts.push({id:crypto.randomUUID(),staff_id:id,started_at:now(),ended_at:null,paused_at:null,pause_seconds:0,breaks:[]});return}if(!sh)return;if(d.jobs.some(j=>j.staff_id===id&&j.running_since))throw new Error('Спочатку призупиніть активну роботу');if(action==='pause')sh.paused_at=now();if(action==='resume'||action==='end'){if(sh.paused_at){sh.pause_seconds+=Math.floor((Date.now()-new Date(sh.paused_at).getTime())/1000);sh.breaks.push({from:sh.paused_at,to:now()});sh.paused_at=null}if(action==='end')sh.ended_at=now()}})},
 async pay(id,amount,method,key,note){mutation(d=>{if(d.payouts.some(p=>p.id===key))return;const e=d.earnings.find(e=>e.id===id)!;if(amount<=0||amount>e.amount-e.paid_amount)throw new Error('Перевірте суму');e.paid_amount+=amount;e.status=e.paid_amount===e.amount?'paid':'accrued';d.payouts.push({id:key,earning_id:id,amount,method,note,created_at:now()})})},
 async photo(){throw new Error('Фото перевіряються з підключеною базою')},async photoUrl(){return ''}}
 return <><nav className="wf-tabs" aria-label="Роль у тесті">{[['owner','Власник'],['ruslan','Руслан'],['armen','Армен'],['payroll','Зарплата']].map(([id,label])=><button className={role===id?'active':''} key={id} onClick={()=>{setRole(id);setSelected(null)}}>{label}</button>)}<button onClick={()=>commit(seed())}>Почати тест заново</button></nav>{role==='owner'?<OwnerToday workflow={workflow} orders={orders} staff={staff} openOrder={setSelected}/>:role==='payroll'?<section className="content"><Payroll workflow={workflow} orders={orders} staff={staff}/></section>:<MasterWorkspace key={role} workflow={workflow} orders={orders} staff={staff} member={staff.find(s=>s.id===role)!}/>} {selected&&<OrderWorkDialog workflow={workflow} order={orders[0]} staff={staff} close={()=>setSelected(null)}/>}</>
}
